"""
v0.3 Phase 0 - additive Learn-mode content enrichment.

The 3-round game reads SERVICE_CARDS directly and never sees these fields, so the
game is unaffected. The Learn endpoints serve ENRICHED copies of the cards with
extra study fields. Defaults are honest: most cards are CLF_SAA only; AIF/MLA tags
are applied only where a service is genuinely relevant.

Future Test/Match question banks will live in sibling JSON/modules. Grading for
those modes is planned to be SERVER-SIDE (answer keys not shipped to the browser).
Not implemented in this phase.
"""
from seed_data import SERVICE_CARDS, BASE_SERVICE_CARDS, SYNERGIES

EXAM_TRACKS = [
    {"id": "CLF_SAA", "name": "CLF / SAA", "description": "Cloud Practitioner and Solutions Architect Associate foundations."},
    {"id": "AIF", "name": "AI Practitioner", "description": "AWS AI and generative AI fundamentals."},
    {"id": "MLA", "name": "ML Associate", "description": "Machine Learning Engineer Associate data and model workflows."},
    {"id": "DEA", "name": "Data Engineer Associate", "description": "Data ingestion, transformation, orchestration, data lakes, warehouses, governance, and quality."},
]

# Per-service curated study content. Anything omitted falls back to safe defaults.
# exam_tracks defaults to ["CLF_SAA"] when not specified here.
_OVERRIDES = {
    "lambda": {"study_tip": "Reach for Lambda first for short, event-driven work. No servers to manage.",
               "use_cases": ["Event-driven APIs", "File processing on upload", "Lightweight cron jobs"],
               "anti_patterns": ["Long-running or heavy-compute jobs", "Steady high-throughput workloads better on containers"]},
    "ec2": {"study_tip": "EC2 gives full control of the OS. Pick it when you need custom runtimes or long-lived servers.",
            "use_cases": ["Legacy or stateful apps", "Custom OS or GPU workloads"],
            "anti_patterns": ["Simple static sites", "Spiky, infrequent traffic better on serverless"]},
    "ecs_fargate": {"study_tip": "Fargate runs containers without managing servers. Good middle ground between Lambda and EC2.",
                    "use_cases": ["Containerized web services", "Steady microservices"],
                    "anti_patterns": ["Tiny one-off tasks better on Lambda"]},
    "ecs_ec2": {"study_tip": "Use ECS on EC2 when you need control over the underlying instances or special hardware.",
                "use_cases": ["Cost tuning at scale", "GPU or specialized instances"],
                "anti_patterns": ["Teams that do not want to manage servers"]},
    "app_runner": {"study_tip": "App Runner deploys a container or repo to a managed URL fast. Great for simple services.",
                   "use_cases": ["Quick container deploys", "Small web APIs"],
                   "anti_patterns": ["Complex networking or fine-grained scaling needs"]},
    "beanstalk": {"study_tip": "Elastic Beanstalk handles provisioning for you. Handy for classic web apps.",
                  "use_cases": ["Traditional web apps", "Quick managed deploys"],
                  "anti_patterns": ["Modern serverless or container-native designs"]},
    "s3": {"study_tip": "S3 is durable object storage and the backbone of most architectures and data lakes.",
           "use_cases": ["Static assets and media", "Data lake storage", "Backups and archives"],
           "anti_patterns": ["Low-latency transactional reads better on a database"],
           "exam_tracks": ["CLF_SAA", "MLA"]},
    "ebs": {"study_tip": "EBS is block storage attached to one EC2 instance. Think of it as the VM's disk.",
            "use_cases": ["Boot volumes", "Databases on EC2"],
            "anti_patterns": ["Shared access across many instances, use EFS"]},
    "efs": {"study_tip": "EFS is a shared file system many instances can mount at once.",
            "use_cases": ["Shared content across instances", "Lift-and-shift file workloads"],
            "anti_patterns": ["Object storage needs better served by S3"]},
    "glacier": {"study_tip": "S3 Glacier is cheap, cold, long-term archive storage. Retrieval is slow.",
                "use_cases": ["Compliance archives", "Rarely accessed backups"],
                "anti_patterns": ["Anything needing fast or frequent access"]},
    "dynamodb": {"study_tip": "DynamoDB is serverless NoSQL with single-digit millisecond reads at any scale.",
                 "use_cases": ["High-scale key-value lookups", "Session and leaderboard data"],
                 "anti_patterns": ["Complex relational joins better on RDS"]},
    "rds": {"study_tip": "RDS is managed relational SQL. Reach for it when you need joins and transactions.",
            "use_cases": ["Transactional apps", "Relational reporting"],
            "anti_patterns": ["Massive web-scale key-value traffic better on DynamoDB"]},
    "aurora_serverless": {"study_tip": "Aurora Serverless scales relational capacity up and down automatically.",
                          "use_cases": ["Variable relational workloads", "Cost-efficient dev and test"],
                          "anti_patterns": ["Predictable steady load may be cheaper on provisioned RDS"]},
    "elasticache": {"study_tip": "ElastiCache (Redis or Memcached) puts a fast cache in front of slower stores.",
                    "use_cases": ["Session caching", "Leaderboards", "Read-heavy hot keys"],
                    "anti_patterns": ["System of record, caches are not durable storage"]},
    "redshift": {"study_tip": "Redshift is a columnar data warehouse for analytics over large datasets.",
                 "use_cases": ["BI dashboards", "Large analytical queries"],
                 "anti_patterns": ["High-frequency transactional writes"],
                 "exam_tracks": ["CLF_SAA", "MLA"]},
    "cloudfront": {"study_tip": "CloudFront is the CDN that caches content at edge locations for low latency.",
                   "use_cases": ["Global static delivery", "Caching in front of S3 or an API"],
                   "anti_patterns": ["Dynamic, uncacheable, per-user data with no edge benefit"]},
    "route53": {"study_tip": "Route 53 is DNS plus health checks and routing policies.",
                "use_cases": ["Domain routing", "Failover and latency-based routing"],
                "anti_patterns": ["Content delivery, that is CloudFront's job"]},
    "api_gateway": {"study_tip": "API Gateway is the managed front door for REST and HTTP APIs.",
                    "use_cases": ["Serverless API entry point", "Throttling and auth at the edge"],
                    "anti_patterns": ["Simple static hosting"]},
    "vpc": {"study_tip": "A VPC is your private network boundary in AWS. Subnets, routing, and isolation live here.",
            "use_cases": ["Network isolation", "Private subnets for databases"],
            "anti_patterns": ["Not a compute or storage service on its own"]},
    "alb": {"study_tip": "ALB load-balances HTTP traffic across targets with path and host routing.",
            "use_cases": ["Container and EC2 web traffic", "Path-based microservice routing"],
            "anti_patterns": ["Pure serverless APIs often use API Gateway instead"]},
    "iam": {"study_tip": "IAM controls who can do what. Least privilege is the rule, not the exception.",
            "use_cases": ["Roles and policies", "Service-to-service permissions"],
            "anti_patterns": ["End-user sign-in, use Cognito for that"]},
    "kms": {"study_tip": "KMS manages encryption keys for data at rest across AWS services.",
            "use_cases": ["Encrypting S3, EBS, RDS", "Key rotation and audit"],
            "anti_patterns": ["Application secrets storage, prefer Secrets Manager"]},
    "waf": {"study_tip": "WAF filters malicious web traffic before it reaches your app.",
            "use_cases": ["Blocking common web exploits", "Rate-based rules"],
            "anti_patterns": ["Internal-only services with no public exposure"]},
    "cognito": {"study_tip": "Cognito handles end-user sign-up and sign-in with user pools.",
                "use_cases": ["App user authentication", "Social and federated login"],
                "anti_patterns": ["AWS resource permissions, that is IAM"]},
    "secrets_manager": {"study_tip": "Secrets Manager stores and rotates credentials and API keys safely.",
                        "use_cases": ["Database credentials", "Third-party API keys"],
                        "anti_patterns": ["Encryption keys themselves, that is KMS"]},
    "kinesis": {"study_tip": "Kinesis ingests high-volume streaming data in real time.",
                "use_cases": ["Clickstream and IoT ingestion", "Real-time pipelines"],
                "anti_patterns": ["Simple decoupled queues better on SQS"],
                "exam_tracks": ["CLF_SAA", "MLA"]},
    "athena": {"study_tip": "Athena runs serverless SQL directly over data in S3. No cluster needed.",
               "use_cases": ["Ad hoc data-lake queries", "Log analysis"],
               "anti_patterns": ["High-concurrency BI better on Redshift"],
               "exam_tracks": ["CLF_SAA", "MLA"]},
    "glue_catalog": {"study_tip": "Glue Data Catalog holds the schema and metadata that power Athena and Redshift.",
                     "use_cases": ["Data-lake metadata", "Schema for serverless SQL"],
                     "anti_patterns": ["Not a query engine by itself"],
                     "exam_tracks": ["CLF_SAA", "MLA"]},
    "sns": {"study_tip": "SNS is pub/sub fan-out messaging. One message, many subscribers.",
            "use_cases": ["Notifications", "Fan-out to multiple consumers"],
            "anti_patterns": ["Durable work queues better on SQS"]},
    "sqs": {"study_tip": "SQS is a durable queue that decouples producers from consumers.",
            "use_cases": ["Buffering bursty work", "Decoupling microservices"],
            "anti_patterns": ["Real-time fan-out better on SNS"]},
    "eventbridge": {"study_tip": "EventBridge routes events between services with rules and schedules.",
                    "use_cases": ["Event-driven workflows", "Scheduled triggers"],
                    "anti_patterns": ["Simple point-to-point queues better on SQS"]},
    "cloudwatch": {"study_tip": "CloudWatch is metrics, logs, and alarms. Your observability hub.",
                   "use_cases": ["Dashboards and alarms", "Centralized logs"],
                   "anti_patterns": ["Not a security threat detector, see GuardDuty"]},
    "bedrock": {"study_tip": "Bedrock gives API access to foundation models for generative AI without managing infrastructure.",
                "use_cases": ["Chatbots and summarization", "Retrieval augmented generation"],
                "anti_patterns": ["Training custom models from scratch, use SageMaker"],
                "exam_tracks": ["CLF_SAA", "AIF", "MLA"]},
    "sagemaker": {"study_tip": "SageMaker builds, trains, and deploys custom machine learning models end to end.",
                  "use_cases": ["Custom model training", "Managed model hosting"],
                  "anti_patterns": ["Simple prompt-only generative tasks fit Bedrock"],
                  "exam_tracks": ["CLF_SAA", "AIF", "MLA"]},
}

# Map of service id -> set of paired service ids, derived from the game's SYNERGIES.
_PAIRINGS = {}
for _a, _b in SYNERGIES:
    _PAIRINGS.setdefault(_a, set()).add(_b)
    _PAIRINGS.setdefault(_b, set()).add(_a)

_TITLE_BY_ID = {c["id"]: c["title"] for c in SERVICE_CARDS}


def _xc(cid, title, category, tracks, front, back, tip, uses=None, antis=None, tags=None):
    """Build a Learn-only concept flashcard. These never enter the Play game."""
    return {
        "id": cid, "title": title, "category": category, "description": back,
        "exam_tracks": tracks, "domains": [], "use_cases": uses or [],
        "common_pairings": [], "anti_patterns": antis or [],
        "study_tip": tip, "flashcard_front": front, "flashcard_back": back,
        "tags": tags or [], "concept_card": True,
    }


# v0.4.0 Phase 5A: original concept flashcards for AIF, MLA, and DEA.
# Synthesized from broad public exam objectives and AWS service knowledge.
_EXTRA_CARDS = [
    # ---------------- AIF (AI Practitioner) ----------------
    _xc("aif_bedrock", "Amazon Bedrock", "AI", ["AIF"],
        "What is Amazon Bedrock?",
        "A managed service that offers foundation models from several providers through one API, with no infrastructure to run.",
        "When a question mentions foundation models without managing servers, think Bedrock.",
        ["Chatbots and summarization", "Retrieval augmented generation"], ["Training custom models from scratch"], ["generative-ai"]),
    _xc("aif_foundation_models", "Foundation Models", "AI", ["AIF"],
        "What is a foundation model?",
        "A large model pretrained on broad data that can be adapted to many tasks such as text generation, summarization, and classification.",
        "Pretrained and general purpose is the key idea.",
        ["Text generation", "Summarization"], ["Narrow single-purpose rules engines"], ["generative-ai"]),
    _xc("aif_prompt_engineering", "Prompt Engineering", "AI", ["AIF"],
        "What is prompt engineering?",
        "The practice of shaping the input instructions and context you give a model to guide the quality and format of its output.",
        "How you ask changes what you get. Clear context and examples help.",
        ["Improving answer quality", "Controlling output format"], ["Assuming output quality is fixed"], ["generative-ai"]),
    _xc("aif_rag", "Retrieval Augmented Generation", "AI", ["AIF"],
        "What does RAG do?",
        "It retrieves relevant context from your own data at query time and adds it to the prompt so the model answers using that context.",
        "Retrieval means pulling in your own data before the model responds.",
        ["Grounded question answering", "Domain-specific assistants"], ["Relying on the base model alone for private data"], ["generative-ai"]),
    _xc("aif_amazon_q", "Amazon Q", "AI", ["AIF"],
        "What is Amazon Q?",
        "A generative AI assistant that can connect to enterprise data and AWS to answer questions and help with tasks.",
        "Think assistant that works across your data and tools.",
        ["Business question answering", "Developer assistance"], ["Training foundation models"], ["generative-ai"]),
    _xc("aif_responsible_ai", "Responsible AI", "AI", ["AIF"],
        "What is responsible AI?",
        "Building AI that is fair, transparent, secure, and accountable, considering impact on people and reducing harm.",
        "Fairness, transparency, privacy, and accountability travel together.",
        ["Governance reviews", "Human oversight"], ["Ignoring model impact on users"], ["responsible-ai"]),
    _xc("aif_bias_fairness", "Bias and Fairness", "AI", ["AIF"],
        "Why do bias and fairness matter?",
        "Skewed or unrepresentative training data can produce unfair outcomes, so teams evaluate and mitigate bias across groups.",
        "Biased data in can mean biased results out.",
        ["Fairness evaluation", "Balanced datasets"], ["Assuming data is neutral by default"], ["responsible-ai"]),
    _xc("aif_model_evaluation", "Model Evaluation Basics", "AI", ["AIF"],
        "Why evaluate a model?",
        "Evaluation measures whether outputs are accurate, relevant, and safe using test data and human review before and after deployment.",
        "You cannot trust what you have not measured.",
        ["Quality checks", "Comparing models"], ["Shipping without evaluation"], ["ai-ml"]),
    _xc("aif_sagemaker_purpose", "SageMaker at a Glance", "AI", ["AIF"],
        "What is Amazon SageMaker used for?",
        "A platform to build, train, tune, and deploy custom machine learning models across the full lifecycle.",
        "Custom model building end to end is SageMaker. Prompt-only tasks fit Bedrock.",
        ["Custom model training", "Managed hosting"], ["Simple prompt-only generative tasks"], ["ai-ml"]),
    _xc("aif_use_case_selection", "AI Use Case Selection", "AI", ["AIF"],
        "How do you pick the right AI approach?",
        "Match the task to the simplest capable option: a managed AI service, a foundation model, or a custom trained model.",
        "Start with the simplest option that solves the problem.",
        ["Choosing managed AI services", "Deciding build versus buy"], ["Over-engineering a simple task"], ["ai-ml"]),
    _xc("aif_security_privacy", "AI Security and Privacy", "Security", ["AIF"],
        "What are AI security and privacy basics?",
        "Protect training and prompt data, control access with least privilege, and avoid exposing sensitive information to models.",
        "Data protection and least privilege still apply to AI workloads.",
        ["Access control for AI data", "Protecting prompts"], ["Sending secrets into prompts"], ["responsible-ai"]),
    _xc("aif_genai_cost", "Cost Awareness for Generative AI", "AI", ["AIF"],
        "What drives generative AI cost?",
        "Token usage, model choice, request volume, and context size influence cost, so pick right-sized models and trim prompts.",
        "Bigger models and longer prompts usually cost more.",
        ["Right-sizing models", "Trimming context"], ["Using the largest model for every task"], ["generative-ai"]),

    # ---------------- MLA (ML Engineer Associate) ----------------
    _xc("mla_training_jobs", "SageMaker Training Jobs", "AI", ["MLA"],
        "What is a SageMaker training job?",
        "A managed job that provisions compute, runs your training code on data, and saves the resulting model artifacts.",
        "Training jobs spin up compute, train, then tear down.",
        ["Training custom models", "Scaling training compute"], ["Long-lived always-on servers for one-off training"], ["ml-engineering"]),
    _xc("mla_endpoints", "SageMaker Endpoints", "AI", ["MLA"],
        "What is a SageMaker endpoint?",
        "A managed, hosted deployment that serves a model for real-time inference over an API.",
        "Endpoints serve real-time predictions.",
        ["Real-time inference", "Low-latency serving"], ["Huge offline scoring better done in batch"], ["ml-engineering"]),
    _xc("mla_feature_store", "SageMaker Feature Store", "AI", ["MLA"],
        "What is a Feature Store?",
        "A central repository for curated features so training and inference use consistent, reusable inputs.",
        "One source of truth for features across training and serving.",
        ["Reusing features", "Consistent training and serving"], ["Recomputing features ad hoc everywhere"], ["ml-engineering"]),
    _xc("mla_model_registry", "SageMaker Model Registry", "AI", ["MLA"],
        "What is a Model Registry?",
        "A catalog that versions models, tracks approval status, and supports promotion from staging to production.",
        "Versioning and approval for models lives in the registry.",
        ["Model versioning", "Deployment approvals"], ["Untracked ad hoc model files"], ["mlops"]),
    _xc("mla_pipelines", "SageMaker Pipelines", "AI", ["MLA"],
        "What are SageMaker Pipelines?",
        "A way to define repeatable ML workflows such as data prep, training, evaluation, and registration as connected steps.",
        "Pipelines make the ML workflow repeatable and automated.",
        ["Automating ML workflows", "Reproducible training"], ["Manual one-off steps for production ML"], ["mlops"]),
    _xc("mla_model_monitoring", "Model Monitoring", "Monitoring", ["MLA"],
        "Why monitor a deployed model?",
        "To detect data drift, quality drops, and changing inputs so you can retrain before performance degrades.",
        "Models decay as the world changes. Watch for drift.",
        ["Drift detection", "Production quality checks"], ["Deploy and forget"], ["mlops"]),
    _xc("mla_data_prep", "Data Preparation for ML", "Analytics", ["MLA"],
        "What is data preparation for ML?",
        "Cleaning, transforming, and engineering features from raw data so a model can learn useful patterns.",
        "Better inputs usually beat fancier models.",
        ["Feature engineering", "Cleaning and labeling"], ["Feeding raw messy data straight to training"], ["ml-engineering"]),
    _xc("mla_overfitting", "Overfitting and Underfitting", "AI", ["MLA"],
        "What are overfitting and underfitting?",
        "Overfitting memorizes training data and fails on new data. Underfitting is too simple to capture the pattern at all.",
        "Overfit clings to noise. Underfit misses the signal.",
        ["Choosing model complexity", "Using validation data"], ["Judging a model only on training accuracy"], ["ai-ml"]),
    _xc("mla_inference_modes", "Batch vs Real-Time Inference", "AI", ["MLA"],
        "Batch or real-time inference?",
        "Real-time endpoints answer per request with low latency. Batch inference scores large datasets on a schedule and can cost less.",
        "Need an instant answer, go real-time. Scoring a big file, go batch.",
        ["Real-time serving", "Scheduled bulk scoring"], ["Real-time endpoints for huge offline jobs"], ["ml-engineering"]),
    _xc("mla_mlops_lifecycle", "MLOps Lifecycle", "AI", ["MLA"],
        "What is the MLOps lifecycle?",
        "The end-to-end loop of data prep, training, evaluation, deployment, monitoring, and retraining, automated for reliability.",
        "MLOps is DevOps discipline applied to machine learning.",
        ["Automating retraining", "Reliable deployments"], ["Manual, unrepeatable ML processes"], ["mlops"]),
    _xc("mla_deployment_tradeoffs", "Model Deployment Tradeoffs", "AI", ["MLA"],
        "What tradeoffs affect model deployment?",
        "Latency, cost, throughput, and freshness shape whether you pick real-time endpoints, batch jobs, or serverless inference.",
        "Balance latency, cost, and scale for the workload.",
        ["Choosing a serving pattern", "Cost versus latency"], ["One pattern for every workload"], ["ml-engineering"]),
    _xc("mla_experiment_tracking", "Experiment Tracking", "AI", ["MLA"],
        "Why track experiments?",
        "Recording parameters, data versions, and metrics lets you compare runs and reproduce the best model.",
        "If you cannot reproduce it, you cannot trust it.",
        ["Comparing runs", "Reproducible results"], ["Losing track of what produced a model"], ["mlops"]),

    # ---------------- DEA (Data Engineer Associate) ----------------
    _xc("dea_s3_data_lake", "Amazon S3 Data Lakes", "Storage", ["DEA"],
        "Why is S3 the core of a data lake?",
        "S3 stores raw and processed data of any format durably and cheaply, decoupling storage from the engines that query it.",
        "Store once in S3, query with many engines.",
        ["Central data lake storage", "Raw and curated zones"], ["Low-latency transactional reads"], ["data-lake"]),
    _xc("dea_glue_crawlers", "AWS Glue Crawlers", "Analytics", ["DEA"],
        "What does a Glue crawler do?",
        "It scans data in sources like S3, infers schema, and populates table definitions in the Glue Data Catalog.",
        "Crawlers discover schema so you do not define it by hand.",
        ["Schema discovery", "Cataloging new data"], ["Frequently changing tiny datasets where manual schema is simpler"], ["etl"]),
    _xc("dea_glue_etl", "AWS Glue ETL", "Analytics", ["DEA"],
        "What is AWS Glue ETL?",
        "A serverless service that runs extract, transform, and load jobs to clean and reshape data between sources and targets.",
        "Serverless ETL without managing clusters.",
        ["Transforming data", "Preparing data for analytics"], ["Ultra-low-latency streaming transforms"], ["etl"]),
    _xc("dea_glue_catalog", "AWS Glue Data Catalog", "Analytics", ["DEA"],
        "What is the Glue Data Catalog?",
        "A central metadata store of table and schema definitions used by Athena, Redshift Spectrum, and Glue.",
        "One catalog of schema powers many query engines.",
        ["Shared schema", "Metadata for serverless SQL"], ["A query engine by itself"], ["metadata"]),
    _xc("dea_athena", "Amazon Athena", "Analytics", ["DEA"],
        "What is Amazon Athena?",
        "A serverless query service that runs standard SQL directly over data in S3 with no cluster to manage.",
        "Serverless SQL over the data lake.",
        ["Ad hoc lake queries", "Log analysis"], ["High-concurrency BI better on a warehouse"], ["query"]),
    _xc("dea_redshift", "Amazon Redshift", "Analytics", ["DEA"],
        "What is Amazon Redshift?",
        "A columnar cloud data warehouse built for fast analytical queries over large, structured datasets.",
        "Warehouse means analytics at scale on structured data.",
        ["BI dashboards", "Large analytical joins"], ["High-frequency transactional writes"], ["warehouse"]),
    _xc("dea_kinesis", "Amazon Kinesis", "Integration", ["DEA"],
        "What is Amazon Kinesis used for?",
        "Ingesting and processing high-volume streaming data in near real time, such as clickstream, logs, and telemetry.",
        "Streaming ingestion in near real time.",
        ["Real-time pipelines", "Clickstream and IoT ingestion"], ["Simple decoupled batch queues"], ["streaming"]),
    _xc("dea_msk", "Amazon MSK", "Integration", ["DEA"],
        "What is Amazon MSK?",
        "A managed Apache Kafka service for building streaming data pipelines and event-driven systems.",
        "Managed Kafka for streaming pipelines.",
        ["Kafka-based streaming", "Event pipelines"], ["Teams wanting zero streaming infrastructure at all"], ["streaming"]),
    _xc("dea_lake_formation", "AWS Lake Formation", "Security", ["DEA"],
        "What does Lake Formation do?",
        "It centralizes data lake security, applying fine-grained access permissions across catalog databases, tables, and columns.",
        "Central, fine-grained governance for the data lake.",
        ["Fine-grained access control", "Data lake governance"], ["Simple single-owner buckets"], ["governance"]),
    _xc("dea_step_functions", "AWS Step Functions", "Integration", ["DEA"],
        "How do Step Functions help data pipelines?",
        "They orchestrate multi-step workflows with state, retries, and branching to coordinate ETL and processing tasks.",
        "Orchestrate ordered steps with retries and branching.",
        ["Pipeline orchestration", "Coordinating ETL steps"], ["A single independent task with no steps"], ["orchestration"]),
    _xc("dea_eventbridge", "Amazon EventBridge", "Integration", ["DEA"],
        "What is EventBridge good for in data workflows?",
        "It routes events between services with rules and schedules to trigger event-driven and scheduled data jobs.",
        "Event-driven and scheduled triggers for pipelines.",
        ["Event-driven jobs", "Scheduled triggers"], ["Simple point-to-point queues"], ["orchestration"]),
    _xc("dea_partitioning", "Data Partitioning", "Analytics", ["DEA"],
        "Why partition data?",
        "Organizing data by keys like date lets query engines scan less data, cutting cost and improving performance.",
        "Good partitions mean less data scanned per query.",
        ["Faster lake queries", "Lower scan cost"], ["Over-partitioning into tiny files"], ["performance"]),
    _xc("dea_data_quality", "Data Quality Checks", "Analytics", ["DEA"],
        "What are data quality checks?",
        "Rules that validate completeness, accuracy, and consistency so bad data is caught before it reaches consumers.",
        "Catch bad data early, before it spreads downstream.",
        ["Validation rules", "Trustworthy pipelines"], ["Assuming source data is always clean"], ["quality"]),
    _xc("dea_lifecycle", "Data Lifecycle Policies", "Storage", ["DEA"],
        "What are data lifecycle policies?",
        "Rules that move or expire data across storage tiers over time, such as archiving cold data to reduce cost.",
        "Age data to cheaper tiers as access drops.",
        ["Tiered storage", "Cost control over time"], ["Keeping hot storage for cold archives"], ["lifecycle"]),
    _xc("dea_batch_vs_stream", "Batch vs Streaming Ingestion", "Integration", ["DEA"],
        "Batch or streaming ingestion?",
        "Batch loads data on a schedule in chunks. Streaming ingests continuously for near real-time needs.",
        "Scheduled chunks are batch. Continuous is streaming.",
        ["Choosing an ingestion pattern", "Latency versus simplicity"], ["Streaming when a nightly batch is enough"], ["ingestion"]),
]


def enrich_cards():
    """Return service cards with additive Learn fields. Game data is left untouched.

    Play-game service cards come first, followed by the Learn-only concept cards
    (AIF, MLA, DEA). The Play game reads SERVICE_CARDS directly and never sees these.
    """
    enriched = []
    for card in BASE_SERVICE_CARDS:
        ov = _OVERRIDES.get(card["id"], {})
        pairings = sorted(_PAIRINGS.get(card["id"], set()))
        enriched.append({
            **card,
            "exam_tracks": ov.get("exam_tracks", ["CLF_SAA"]),
            "domains": ov.get("domains", []),
            "use_cases": ov.get("use_cases", []),
            "common_pairings": [{"id": p, "title": _TITLE_BY_ID.get(p, p)} for p in pairings],
            "anti_patterns": ov.get("anti_patterns", []),
            "study_tip": ov.get("study_tip", f"{card['title']} sits in the {card['category']} category. Learn where it fits in an architecture."),
            "flashcard_front": ov.get("flashcard_front", card["title"]),
            "flashcard_back": ov.get("flashcard_back", card["description"]),
        })
    enriched.extend(_EXTRA_CARDS)
    return enriched
