"""
v0.4.2 Phase 5C: Track-aware Play expansion.

Original, synthesized educational content for track-aware Play mode. Adds
domain service cards and Play scenarios for AIF, MLA, and DEA, plus refined
CLF/SAA scenarios. All content is original and derived from broad public AWS
service knowledge and certification objectives. No official exam wording is
copied.

This module is pure data with no imports from seed_data, so it can be safely
imported and merged by seed_data at load time without circular imports.

Card schema matches seed_data SERVICE_CARDS and adds a `tracks` list.
Scenario schema matches seed_data SCENARIOS and adds a `tracks` list.
The scoring engine reads core_service_ids, supporting_service_ids,
distractor_service_ids, ideal_combos, and min/max services. ideal_tags and
ideal_categories are display-only and do not affect scoring.
"""

DEFAULT_CARD_TRACK = "CLF_SAA"

# Certification tracks assigned to the existing base service cards. Every base
# card keeps CLF_SAA so existing CLF/SAA Play behavior is unchanged.
BASE_CARD_TRACKS = {
    "lambda": ["CLF_SAA", "AIF", "MLA", "DEA"],
    "ec2": ["CLF_SAA", "MLA"],
    "ecs_fargate": ["CLF_SAA", "MLA"],
    "ecs_ec2": ["CLF_SAA"],
    "app_runner": ["CLF_SAA"],
    "beanstalk": ["CLF_SAA"],
    "s3": ["CLF_SAA", "AIF", "MLA", "DEA"],
    "ebs": ["CLF_SAA"],
    "efs": ["CLF_SAA", "MLA"],
    "glacier": ["CLF_SAA", "DEA"],
    "dynamodb": ["CLF_SAA", "AIF", "DEA"],
    "rds": ["CLF_SAA", "DEA"],
    "aurora_serverless": ["CLF_SAA"],
    "elasticache": ["CLF_SAA"],
    "redshift": ["CLF_SAA", "DEA", "MLA"],
    "cloudfront": ["CLF_SAA"],
    "route53": ["CLF_SAA"],
    "api_gateway": ["CLF_SAA", "AIF", "MLA"],
    "vpc": ["CLF_SAA"],
    "alb": ["CLF_SAA"],
    "iam": ["CLF_SAA", "AIF", "MLA", "DEA"],
    "kms": ["CLF_SAA", "MLA", "DEA"],
    "waf": ["CLF_SAA"],
    "cognito": ["CLF_SAA", "AIF"],
    "secrets_manager": ["CLF_SAA"],
    "kinesis": ["CLF_SAA", "DEA", "MLA"],
    "athena": ["CLF_SAA", "DEA", "MLA"],
    "glue_catalog": ["CLF_SAA", "DEA", "MLA"],
    "sns": ["CLF_SAA", "AIF", "DEA"],
    "sqs": ["CLF_SAA", "DEA"],
    "eventbridge": ["CLF_SAA", "DEA"],
    "cloudwatch": ["CLF_SAA", "AIF", "MLA", "DEA"],
    "bedrock": ["CLF_SAA", "AIF"],
    "sagemaker": ["CLF_SAA", "AIF", "MLA"],
}

# All existing scenarios are cloud foundations and architecture scenarios.
BASE_SCENARIO_TRACKS = {
    "photo_sharing": ["CLF_SAA"],
    "fintech_api": ["CLF_SAA"],
    "iot_telemetry": ["CLF_SAA", "DEA"],
    "static_blog": ["CLF_SAA"],
    "chat_app": ["CLF_SAA"],
    "ecommerce": ["CLF_SAA"],
    "ml_batch": ["CLF_SAA", "MLA"],
    "internal_dashboard": ["CLF_SAA", "DEA"],
    "gaming_leaderboard": ["CLF_SAA"],
    "compliance_logs": ["CLF_SAA"],
}


def _card(cid, title, category, tracks, description, tooltip, tags,
          cost, security, scalability, complexity, serverless, difficulty=2):
    return {
        "id": cid, "title": title, "category": category,
        "description": description, "tooltip": tooltip,
        "difficulty": difficulty, "tags": tags,
        "cost": cost, "security": security, "scalability": scalability,
        "complexity": complexity, "serverless": serverless, "tracks": tracks,
    }


EXPANSION_CARDS = [
    # ---------------- AIF service cards ----------------
    _card("titan", "Amazon Titan", "AI", ["AIF"],
          "Amazon foundation models on Bedrock for text generation and embeddings.",
          "Titan embeddings power semantic search and RAG retrieval.",
          ["genai", "embeddings", "foundation-model", "serverless", "ai"],
          3, 4, 5, 2, True),
    _card("nova", "Amazon Nova", "AI", ["AIF"],
          "Amazon Nova multimodal foundation models on Bedrock for text, image, and video understanding.",
          "Reach for Nova when a task spans multiple modalities.",
          ["genai", "multimodal", "foundation-model", "serverless", "ai"],
          3, 4, 5, 2, True),
    _card("amazon_q", "Amazon Q", "AI", ["AIF"],
          "Generative AI assistant that connects to enterprise data and AWS to answer questions.",
          "An assistant that works across your data and tools.",
          ["genai", "assistant", "serverless", "ai"],
          3, 4, 5, 2, True),
    _card("lex", "Amazon Lex", "AI", ["AIF"],
          "Build conversational chatbots and voice bots with automatic speech recognition and intent handling.",
          "Intent-based conversational bots for chat and voice.",
          ["chatbot", "conversational", "serverless", "ai"],
          2, 4, 5, 2, True),
    _card("textract", "Amazon Textract", "AI", ["AIF"],
          "Extract text, forms, and tables from scanned documents and images.",
          "Turn documents and forms into structured data.",
          ["document", "ocr", "extraction", "serverless", "ai"],
          2, 4, 5, 2, True),
    _card("comprehend", "Amazon Comprehend", "AI", ["AIF"],
          "Natural language processing for sentiment, entities, and key phrases.",
          "NLP for sentiment and entity extraction.",
          ["nlp", "sentiment", "serverless", "ai"],
          2, 4, 5, 2, True),
    _card("transcribe", "Amazon Transcribe", "AI", ["AIF"],
          "Automatic speech to text for audio and video.",
          "Convert speech into searchable text.",
          ["speech-to-text", "audio", "serverless", "ai"],
          2, 4, 5, 2, True),
    _card("polly", "Amazon Polly", "AI", ["AIF"],
          "Text to lifelike speech synthesis in many voices and languages.",
          "Turn text into natural sounding speech.",
          ["text-to-speech", "audio", "serverless", "ai"],
          2, 4, 5, 2, True),
    _card("rekognition", "Amazon Rekognition", "AI", ["AIF"],
          "Image and video analysis for labels, moderation, and detection.",
          "Analyze and moderate images and video.",
          ["vision", "image", "moderation", "serverless", "ai"],
          2, 4, 5, 2, True),
    _card("bedrock_kb", "Bedrock Knowledge Bases", "AI", ["AIF"],
          "Managed retrieval layer that grounds foundation models on your own data for RAG.",
          "Retrieval augmented generation without building a vector pipeline.",
          ["rag", "retrieval", "genai", "serverless", "ai"],
          3, 4, 5, 2, True),
    _card("bedrock_guardrails", "Bedrock Guardrails", "Security", ["AIF"],
          "Policy controls that filter harmful content and enforce responsible AI on model responses.",
          "Add safety and content policy to generative AI apps.",
          ["responsible-ai", "safety", "guardrails", "serverless", "security", "ai"],
          2, 5, 5, 2, True),

    # ---------------- MLA service cards ----------------
    _card("sagemaker_training", "SageMaker Training", "AI", ["MLA"],
          "Managed training jobs that provision compute, train on your data, and save model artifacts.",
          "Spin up compute, train, then tear down automatically.",
          ["ml", "train", "ai"],
          4, 4, 4, 3, False, difficulty=3),
    _card("sagemaker_endpoint", "SageMaker Endpoint", "AI", ["MLA"],
          "Managed real-time inference endpoints that serve a model over an API.",
          "Serve low-latency real-time predictions.",
          ["ml", "inference", "endpoint", "ai"],
          4, 4, 4, 3, False, difficulty=3),
    _card("sagemaker_batch", "SageMaker Batch Transform", "AI", ["MLA"],
          "Run inference over large datasets on a schedule without a persistent endpoint.",
          "Score big datasets in batch to save cost.",
          ["ml", "batch", "inference", "ai"],
          3, 4, 4, 3, False, difficulty=3),
    _card("sagemaker_pipelines", "SageMaker Pipelines", "AI", ["MLA"],
          "Define repeatable ML workflows for data prep, training, evaluation, and registration.",
          "Automate the ML workflow end to end.",
          ["ml", "mlops", "pipeline", "ai"],
          3, 4, 4, 3, True, difficulty=3),
    _card("sagemaker_registry", "SageMaker Model Registry", "AI", ["MLA"],
          "Catalog that versions models, tracks approval status, and supports promotion to production.",
          "Version and approve models before deployment.",
          ["ml", "mlops", "versioning", "ai"],
          2, 4, 5, 2, True),
    _card("sagemaker_feature_store", "SageMaker Feature Store", "AI", ["MLA"],
          "Central repository for curated features shared across training and inference.",
          "One source of truth for features.",
          ["ml", "features", "ai"],
          3, 4, 4, 3, True),
    _card("sagemaker_model_monitor", "SageMaker Model Monitor", "Monitoring", ["MLA"],
          "Detects data drift and quality drops on deployed models so you can retrain in time.",
          "Watch production models for drift.",
          ["ml", "monitoring", "drift", "mlops", "ai"],
          2, 4, 5, 2, True),
    _card("ecr", "Amazon ECR", "Compute", ["MLA"],
          "Managed container registry for storing and versioning ML and application images.",
          "Store the container images your training and serving use.",
          ["container", "registry", "images"],
          2, 4, 5, 2, True),

    # ---------------- DEA service cards ----------------
    _card("glue", "AWS Glue", "Analytics", ["DEA"],
          "Serverless extract, transform, and load jobs that clean and reshape data.",
          "Serverless ETL without managing clusters.",
          ["etl", "serverless", "transform", "analytics", "data-lake"],
          2, 4, 5, 3, True),
    _card("glue_crawler", "Glue Crawler", "Analytics", ["DEA"],
          "Scans sources like S3, infers schema, and populates the Glue Data Catalog.",
          "Discover schema automatically instead of by hand.",
          ["schema", "crawler", "serverless", "analytics", "data-lake"],
          1, 4, 5, 2, True),
    _card("kinesis_firehose", "Kinesis Data Firehose", "Analytics", ["DEA"],
          "Serverless delivery stream that buffers and lands streaming data into S3, Redshift, or other targets.",
          "The easiest path from a stream into the data lake.",
          ["stream", "delivery", "serverless", "analytics", "data-lake"],
          2, 4, 5, 2, True),
    _card("msk", "Amazon MSK", "Analytics", ["DEA"],
          "Managed Apache Kafka for building streaming data pipelines and event-driven systems.",
          "Managed Kafka for high-throughput streaming.",
          ["stream", "kafka", "analytics"],
          4, 4, 5, 4, False, difficulty=3),
    _card("lake_formation", "Lake Formation", "Security", ["DEA"],
          "Centralizes data lake security with fine-grained permissions across databases, tables, and columns.",
          "Fine-grained governance for the data lake.",
          ["governance", "security", "data-lake", "permissions"],
          2, 5, 5, 3, True),
    _card("step_functions", "Step Functions", "Integration", ["DEA", "MLA"],
          "Orchestrates multi-step workflows with state, retries, and branching to coordinate pipelines.",
          "Coordinate ordered steps with retries and branching.",
          ["orchestration", "workflow", "serverless", "integration"],
          2, 4, 5, 2, True),
    _card("quicksight", "Amazon QuickSight", "Analytics", ["DEA"],
          "Serverless business intelligence service for interactive dashboards and visualizations.",
          "Build BI dashboards on top of the warehouse or lake.",
          ["bi", "dashboards", "visualization", "serverless", "analytics"],
          2, 4, 5, 2, True),
]


def _scn(sid, title, tracks, prompt, hint_text, hint_kw, core, supporting,
         distractors, combos, min_s=3, max_s=6, difficulty=2,
         ideal_categories=None, ideal_tags=None):
    return {
        "id": sid, "title": title, "tracks": tracks, "prompt": prompt,
        "hint": {"text": hint_text, "kw": hint_kw},
        "ideal_categories": ideal_categories or [], "ideal_tags": ideal_tags or [],
        "min_services": min_s, "max_services": max_s, "difficulty": difficulty,
        "core_service_ids": core, "supporting_service_ids": supporting,
        "distractor_service_ids": distractors, "ideal_combos": combos,
    }


EXPANSION_SCENARIOS = [
    # ---------------- AIF Play scenarios ----------------
    _scn("aif_support_assistant", "Generative AI Support Assistant", ["AIF"],
         "A company wants a chat assistant that answers customer questions using a foundation model, with content safety controls.",
         "Start with a managed foundation model behind an API, then add safety controls.",
         ["generative model", "guardrails", "serverless api"],
         ["bedrock", "lambda", "api_gateway"],
         ["bedrock_guardrails", "cognito", "cloudwatch", "s3"],
         ["redshift", "sagemaker_training", "kinesis", "ec2"],
         [["bedrock", "lambda", "api_gateway"],
          ["bedrock", "lambda", "api_gateway", "bedrock_guardrails"]]),
    _scn("aif_rag_docs", "RAG Over Company Documents", ["AIF"],
         "Employees ask questions and expect answers grounded in internal documents rather than the base model alone.",
         "Ground the model on your own data with a managed retrieval layer and embeddings.",
         ["retrieval", "embeddings", "object storage"],
         ["bedrock", "bedrock_kb", "s3", "lambda"],
         ["titan", "api_gateway", "cloudwatch", "iam"],
         ["redshift", "msk", "ec2", "polly"],
         [["bedrock", "bedrock_kb", "s3", "lambda"],
          ["bedrock", "bedrock_kb", "s3", "api_gateway"]]),
    _scn("aif_doc_extraction", "Document Extraction Pipeline", ["AIF"],
         "Scanned invoices arrive daily and the team needs the text, forms, and tables pulled out automatically.",
         "Use a document extraction service, land results in storage, and process with functions.",
         ["document extraction", "object storage", "serverless"],
         ["textract", "s3", "lambda"],
         ["comprehend", "dynamodb", "cloudwatch"],
         ["rekognition", "redshift", "ec2", "polly"],
         [["textract", "s3", "lambda"],
          ["textract", "s3", "lambda", "comprehend"]]),
    _scn("aif_feedback_nlp", "Customer Feedback NLP", ["AIF"],
         "Product reviews and support tickets need automatic sentiment and key phrase analysis at scale.",
         "Reach for a managed NLP service, store text in object storage, and glue it with functions.",
         ["nlp", "sentiment", "serverless"],
         ["comprehend", "s3", "lambda"],
         ["api_gateway", "dynamodb", "cloudwatch"],
         ["transcribe", "rekognition", "ec2", "msk"],
         [["comprehend", "s3", "lambda"],
          ["comprehend", "lambda", "api_gateway"]]),
    _scn("aif_voice_workflow", "Voice Note Transcription and Reply", ["AIF"],
         "Voice notes must be transcribed to text and a spoken reply generated back to the caller.",
         "Combine speech to text and text to speech, coordinated by functions and storage.",
         ["speech to text", "text to speech", "serverless"],
         ["transcribe", "polly", "lambda", "s3"],
         ["comprehend", "api_gateway", "cloudwatch"],
         ["rekognition", "redshift", "ec2"],
         [["transcribe", "polly", "lambda", "s3"],
          ["transcribe", "lambda", "polly"]], min_s=3, max_s=5),
    _scn("aif_image_moderation", "Image Moderation Service", ["AIF"],
         "User uploaded images must be scanned for unsafe content before they go live, with alerts on flags.",
         "Analyze images with a vision service, store them, and notify on flagged content.",
         ["image analysis", "moderation", "notification"],
         ["rekognition", "s3", "lambda"],
         ["sns", "dynamodb", "cloudwatch"],
         ["textract", "transcribe", "ec2", "redshift"],
         [["rekognition", "s3", "lambda"],
          ["rekognition", "s3", "lambda", "sns"]]),
    _scn("aif_booking_bot", "Conversational Booking Bot", ["AIF"],
         "A restaurant wants a chatbot that takes reservations and stores them, with sign in for returning guests.",
         "Use a conversational bot service with functions and a fast data store.",
         ["chatbot", "serverless", "nosql"],
         ["lex", "lambda", "dynamodb"],
         ["cognito", "api_gateway", "cloudwatch"],
         ["rekognition", "redshift", "ec2", "msk"],
         [["lex", "lambda", "dynamodb"],
          ["lex", "lambda", "dynamodb", "cognito"]]),
    _scn("aif_multimodal_studio", "Multimodal Content Studio", ["AIF"],
         "A team generates marketing text and analyzes product images using multimodal generative AI, with an internal assistant for staff.",
         "Use a multimodal foundation model on Bedrock, exposed through an API, with an enterprise assistant.",
         ["multimodal", "generative model", "assistant"],
         ["nova", "bedrock", "lambda", "s3"],
         ["amazon_q", "api_gateway", "bedrock_guardrails", "cloudwatch"],
         ["sagemaker_training", "redshift", "ec2"],
         [["nova", "bedrock", "lambda", "s3"],
          ["nova", "bedrock", "api_gateway", "lambda"]]),

    # ---------------- MLA Play scenarios ----------------
    _scn("mla_train_serve", "Train and Serve a Model", ["MLA"],
         "A team trains a custom model on stored data and serves it for real-time predictions through an endpoint.",
         "Train with a managed job, keep artifacts and images in storage, then host an endpoint.",
         ["training job", "endpoint", "artifacts"],
         ["sagemaker_training", "sagemaker_endpoint", "s3"],
         ["ecr", "cloudwatch", "iam"],
         ["redshift", "kinesis", "bedrock", "ec2"],
         [["sagemaker_training", "sagemaker_endpoint", "s3"],
          ["sagemaker_training", "sagemaker_endpoint", "s3", "ecr"]]),
    _scn("mla_batch_scoring", "Nightly Batch Scoring", ["MLA"],
         "A model scores millions of records every night. There is no need for an always on endpoint.",
         "Use batch inference over data in the lake instead of a persistent endpoint.",
         ["batch inference", "object storage", "scheduled"],
         ["sagemaker_batch", "s3", "sagemaker_training"],
         ["athena", "cloudwatch", "iam"],
         ["sagemaker_endpoint", "bedrock", "ec2", "msk"],
         [["sagemaker_batch", "s3", "sagemaker_training"],
          ["sagemaker_batch", "s3", "athena"]], min_s=3, max_s=5),
    _scn("mla_retrain_pipeline", "Automated Retraining Pipeline", ["MLA"],
         "The team wants repeatable training, evaluation, and model versioning that runs without manual steps.",
         "Automate the workflow and register versioned models for approval.",
         ["pipeline", "versioning", "automation"],
         ["sagemaker_pipelines", "sagemaker_training", "sagemaker_registry", "s3"],
         ["cloudwatch", "iam", "ecr"],
         ["bedrock", "redshift", "ec2"],
         [["sagemaker_pipelines", "sagemaker_training", "sagemaker_registry", "s3"],
          ["sagemaker_pipelines", "sagemaker_training", "s3"]], min_s=3, max_s=6, difficulty=3),
    _scn("mla_feature_pipeline", "Consistent Feature Pipeline", ["MLA"],
         "Training and serving must use the same curated features to avoid skew.",
         "Centralize features so training and inference share one source of truth.",
         ["feature store", "consistency", "object storage"],
         ["sagemaker_feature_store", "s3", "sagemaker_training"],
         ["athena", "glue_catalog", "cloudwatch"],
         ["bedrock", "ec2", "redshift"],
         [["sagemaker_feature_store", "s3", "sagemaker_training"],
          ["sagemaker_feature_store", "sagemaker_training", "athena"]]),
    _scn("mla_drift_monitor", "Detect Model Drift in Production", ["MLA"],
         "A live model slowly degrades. The team needs to detect drift and alert before quality drops too far.",
         "Monitor the endpoint for drift and alert through notifications.",
         ["drift", "monitoring", "alerts"],
         ["sagemaker_model_monitor", "sagemaker_endpoint", "cloudwatch"],
         ["s3", "sns", "iam"],
         ["bedrock", "redshift", "ec2"],
         [["sagemaker_model_monitor", "sagemaker_endpoint", "cloudwatch"],
          ["sagemaker_model_monitor", "sagemaker_endpoint", "cloudwatch", "sns"]], min_s=3, max_s=5),
    _scn("mla_realtime_api", "Low Latency Prediction API", ["MLA"],
         "A product needs sub-second predictions exposed as an API for a web app.",
         "Front a real-time endpoint with an API and functions.",
         ["real-time", "endpoint", "api"],
         ["sagemaker_endpoint", "api_gateway", "lambda"],
         ["cloudwatch", "s3", "iam"],
         ["sagemaker_batch", "redshift", "ec2"],
         [["sagemaker_endpoint", "api_gateway", "lambda"],
          ["sagemaker_endpoint", "lambda", "cloudwatch"]]),
    _scn("mla_feature_engineering", "Feature Engineering at Scale", ["MLA"],
         "Raw event data must be cleaned and turned into model ready features from the data lake.",
         "Query and shape lake data, then store curated features for reuse.",
         ["feature engineering", "data lake", "query"],
         ["glue_catalog", "athena", "s3"],
         ["sagemaker_feature_store", "cloudwatch", "iam"],
         ["bedrock", "ec2", "redshift"],
         [["glue_catalog", "athena", "s3"],
          ["athena", "s3", "sagemaker_feature_store"]]),
    _scn("mla_cost_aware_serving", "Cost Aware Serving Choice", ["MLA"],
         "Predictions are needed a few times a day over large files. An always on endpoint would waste money.",
         "Prefer batch scoring for large periodic jobs to control cost.",
         ["cost", "batch", "object storage"],
         ["sagemaker_batch", "s3", "cloudwatch"],
         ["sagemaker_endpoint", "iam", "athena"],
         ["bedrock", "ec2", "redshift"],
         [["sagemaker_batch", "s3", "cloudwatch"],
          ["sagemaker_batch", "s3", "athena"]], min_s=3, max_s=5),

    # ---------------- DEA Play scenarios ----------------
    _scn("dea_data_lake", "Data Lake Foundation", ["DEA"],
         "Raw files land in object storage and analysts want to query them with SQL without managing servers.",
         "Crawl the data to build a catalog, then query it serverlessly.",
         ["data lake", "catalog", "serverless sql"],
         ["s3", "glue_crawler", "glue_catalog", "athena"],
         ["iam", "cloudwatch", "lake_formation"],
         ["rds", "ec2", "sagemaker_endpoint"],
         [["s3", "glue_crawler", "glue_catalog", "athena"],
          ["s3", "glue_catalog", "athena"]]),
    _scn("dea_etl_curated", "ETL to a Curated Zone", ["DEA"],
         "Raw data must be cleaned and reshaped into a curated zone for downstream analytics.",
         "Run serverless ETL and keep schema in the catalog.",
         ["etl", "transform", "catalog"],
         ["glue", "s3", "glue_catalog"],
         ["step_functions", "cloudwatch", "athena"],
         ["ec2", "rds", "bedrock"],
         [["glue", "s3", "glue_catalog"],
          ["glue", "s3", "athena"]]),
    _scn("dea_streaming_ingest", "Streaming Clickstream Ingestion", ["DEA"],
         "A high-volume clickstream must be ingested continuously and landed in the data lake for analysis.",
         "Ingest with a stream, deliver into storage, then query.",
         ["streaming", "delivery", "data lake"],
         ["kinesis", "kinesis_firehose", "s3"],
         ["lambda", "cloudwatch", "athena"],
         ["rds", "ec2", "redshift"],
         [["kinesis", "kinesis_firehose", "s3"],
          ["kinesis_firehose", "s3", "athena"]]),
    _scn("dea_kafka_pipeline", "Kafka Streaming Pipeline", ["DEA"],
         "A team standardizes on Kafka for event streaming and needs the events processed and stored.",
         "Use managed Kafka, process with functions, and land in the lake.",
         ["kafka", "streaming", "object storage"],
         ["msk", "lambda", "s3"],
         ["cloudwatch", "glue_catalog", "athena"],
         ["rds", "ec2", "bedrock"],
         [["msk", "lambda", "s3"],
          ["msk", "lambda", "s3", "athena"]], difficulty=3),
    _scn("dea_warehouse_bi", "Warehouse and Dashboards", ["DEA"],
         "Business users need fast dashboards over large structured datasets refreshed from the lake.",
         "Load a warehouse from storage and visualize with a BI service.",
         ["warehouse", "bi", "dashboards"],
         ["redshift", "s3", "quicksight"],
         ["glue_catalog", "iam", "athena"],
         ["dynamodb", "ec2", "sagemaker_endpoint"],
         [["redshift", "s3", "quicksight"],
          ["redshift", "s3", "glue_catalog"]]),
    _scn("dea_orchestration", "Orchestrated ETL Workflow", ["DEA"],
         "A multi-step ETL job must run in order with retries and clear failure handling.",
         "Orchestrate the steps and run serverless ETL between them.",
         ["orchestration", "etl", "retries"],
         ["step_functions", "glue", "s3"],
         ["eventbridge", "cloudwatch", "athena"],
         ["ec2", "rds", "bedrock"],
         [["step_functions", "glue", "s3"],
          ["step_functions", "glue", "s3", "eventbridge"]]),
    _scn("dea_governance", "Fine Grained Lake Governance", ["DEA"],
         "Different teams may only see certain tables and columns in the shared data lake.",
         "Apply fine-grained permissions centrally over the catalog.",
         ["governance", "permissions", "catalog"],
         ["lake_formation", "glue_catalog", "s3"],
         ["iam", "athena", "cloudwatch"],
         ["ec2", "rds", "bedrock"],
         [["lake_formation", "glue_catalog", "s3"],
          ["lake_formation", "glue_catalog", "s3", "athena"]]),
    _scn("dea_event_driven", "Event Driven Scheduled Pipeline", ["DEA"],
         "New files should trigger processing automatically and a summary job should run on a schedule.",
         "Trigger functions on events and schedule work with an event bus.",
         ["event-driven", "scheduled", "serverless"],
         ["eventbridge", "lambda", "s3"],
         ["step_functions", "glue", "cloudwatch"],
         ["ec2", "rds", "redshift"],
         [["eventbridge", "lambda", "s3"],
          ["eventbridge", "lambda", "glue", "s3"]]),

    # ---------------- CLF/SAA refined Play scenarios ----------------
    _scn("clf_secure_three_tier", "Secure Private Three Tier App", ["CLF_SAA"],
         "A web app must run in private subnets behind a load balancer with a relational database and strong isolation.",
         "Put compute and data in private subnets behind a load balancer and protect the edge.",
         ["private subnet", "load balancer", "relational"],
         ["vpc", "alb", "ecs_fargate", "rds"],
         ["waf", "cloudwatch", "iam", "kms", "ec2"],
         ["dynamodb", "lambda", "sagemaker", "kinesis"],
         [["vpc", "alb", "ecs_fargate", "rds"],
          ["vpc", "alb", "ec2", "rds"]], min_s=4, max_s=6),
    _scn("clf_backup_dr", "Backup and Disaster Recovery", ["CLF_SAA"],
         "Critical data needs durable backups, cheap long-term archive, and DNS failover to a standby region.",
         "Store durable backups, archive cold copies, and route with health checks.",
         ["backup", "archive", "failover"],
         ["s3", "glacier", "route53", "rds"],
         ["cloudwatch", "kms", "iam"],
         ["kinesis", "sagemaker", "lambda", "dynamodb"],
         [["s3", "glacier", "route53"],
          ["s3", "glacier", "rds", "route53"]], min_s=3, max_s=5),
    _scn("clf_observability", "Observability and Alerting", ["CLF_SAA"],
         "A serverless workload needs centralized logs, metrics, alarms, and alerting on failures.",
         "Centralize metrics and logs, then alert through notifications.",
         ["logs", "metrics", "alerts"],
         ["cloudwatch", "lambda", "sns"],
         ["iam", "s3", "api_gateway"],
         ["redshift", "sagemaker", "kinesis", "ec2"],
         [["cloudwatch", "lambda", "sns"],
          ["cloudwatch", "lambda", "sns", "s3"]], min_s=3, max_s=5),
    _scn("clf_decoupled_orders", "Decoupled Order Processing", ["CLF_SAA"],
         "Order spikes should not overwhelm the backend. Requests should be buffered and processed reliably.",
         "Decouple the front door from processing with a queue and a fast store.",
         ["queue", "decoupled", "serverless"],
         ["api_gateway", "lambda", "sqs", "dynamodb"],
         ["sns", "cloudwatch", "eventbridge"],
         ["rds", "redshift", "sagemaker", "kinesis"],
         [["api_gateway", "lambda", "sqs", "dynamodb"],
          ["api_gateway", "sqs", "lambda", "sns"]], min_s=4, max_s=6),
]

# New synergy pairs so domain designs earn a fair synergy bonus.
EXPANSION_SYNERGIES = [
    ("bedrock", "bedrock_kb"),
    ("bedrock", "bedrock_guardrails"),
    ("bedrock", "titan"),
    ("bedrock", "nova"),
    ("bedrock_kb", "s3"),
    ("bedrock_kb", "titan"),
    ("textract", "comprehend"),
    ("textract", "s3"),
    ("comprehend", "s3"),
    ("transcribe", "polly"),
    ("transcribe", "s3"),
    ("rekognition", "s3"),
    ("rekognition", "sns"),
    ("lex", "lambda"),
    ("lex", "dynamodb"),
    ("nova", "s3"),
    ("sagemaker_training", "s3"),
    ("sagemaker_training", "ecr"),
    ("sagemaker_training", "sagemaker_endpoint"),
    ("sagemaker_training", "sagemaker_registry"),
    ("sagemaker_pipelines", "sagemaker_training"),
    ("sagemaker_pipelines", "sagemaker_registry"),
    ("sagemaker_endpoint", "api_gateway"),
    ("sagemaker_endpoint", "sagemaker_model_monitor"),
    ("sagemaker_model_monitor", "cloudwatch"),
    ("sagemaker_feature_store", "s3"),
    ("sagemaker_feature_store", "sagemaker_training"),
    ("sagemaker_batch", "s3"),
    ("glue", "s3"),
    ("glue", "glue_catalog"),
    ("glue_crawler", "glue_catalog"),
    ("glue_crawler", "s3"),
    ("glue_catalog", "athena"),
    ("kinesis", "kinesis_firehose"),
    ("kinesis_firehose", "s3"),
    ("msk", "lambda"),
    ("lake_formation", "glue_catalog"),
    ("step_functions", "glue"),
    ("step_functions", "eventbridge"),
    ("redshift", "quicksight"),
    ("quicksight", "athena"),
]
