"""
Seed data for AWS CloudForge Cards.
Adding more cards later: append to SERVICE_CARDS / SCENARIOS / CONSTRAINTS.
Each service card has:
  - cost / security / scalability / complexity rated 1-5
  - serverless flag
  - tags (free-form keywords used by the scoring engine for ideal-fit matching)
"""

CONSTRAINTS = [
    {"id": "low_cost", "name": "Low Cost", "color": "yellow",
     "description": "Minimize spend. Prefer pay-per-use, free tiers, lean footprint."},
    {"id": "high_availability", "name": "High Availability", "color": "blue",
     "description": "Survive zone/region failures. Replicas, multi-AZ, failover."},
    {"id": "serverless", "name": "Serverless", "color": "green",
     "description": "No servers to manage. Auto-scaling, event driven."},
    {"id": "secure", "name": "Secure", "color": "red",
     "description": "Strong auth, encryption, least privilege, audit trails."},
    {"id": "scalable", "name": "Scalable", "color": "blue",
     "description": "Handle 10x or 1000x traffic gracefully."},
    {"id": "beginner_friendly", "name": "Beginner Friendly", "color": "green",
     "description": "Low operational complexity. Easy to learn and operate."},
    {"id": "low_latency", "name": "Low Latency", "color": "yellow",
     "description": "Sub-100ms response. Caching, edge, in-memory layers."},
    {"id": "observability", "name": "Observability", "color": "blue",
     "description": "Logs, metrics, traces. Know what is happening in prod."},
]

# 30 service cards — categories: Compute, Storage, Database, Network, Security, Analytics, Integration, Monitoring
SERVICE_CARDS = [
    # Compute (6)
    {"id": "lambda", "title": "Lambda", "category": "Compute",
     "description": "Run code without provisioning servers. Pay per ms of execution.",
     "tooltip": "Best for event-driven workloads, short tasks, glue between services.",
     "difficulty": 1, "tags": ["serverless", "event", "api", "glue", "scale"],
     "cost": 1, "security": 4, "scalability": 5, "complexity": 2, "serverless": True},
    {"id": "ec2", "title": "EC2", "category": "Compute",
     "description": "Virtual machines in the cloud. Full OS control.",
     "tooltip": "Use when you need stateful workloads or custom OS.",
     "difficulty": 2, "tags": ["vm", "compute", "stateful"],
     "cost": 4, "security": 3, "scalability": 3, "complexity": 3, "serverless": False},
    {"id": "ecs_fargate", "title": "ECS on Fargate", "category": "Compute",
     "description": "Run containers without managing servers.",
     "tooltip": "Container workloads with no node management.",
     "difficulty": 2, "tags": ["container", "serverless", "scale"],
     "cost": 3, "security": 4, "scalability": 4, "complexity": 3, "serverless": True},
    {"id": "ecs_ec2", "title": "ECS on EC2", "category": "Compute",
     "description": "Container orchestration on managed EC2 nodes.",
     "tooltip": "Containers where you control the host.",
     "difficulty": 3, "tags": ["container", "cluster"],
     "cost": 3, "security": 3, "scalability": 4, "complexity": 4, "serverless": False},
    {"id": "app_runner", "title": "App Runner", "category": "Compute",
     "description": "Deploy web apps from source or container with zero infra.",
     "tooltip": "Fastest way to ship a containerized web service.",
     "difficulty": 1, "tags": ["web", "container", "beginner", "serverless"],
     "cost": 3, "security": 4, "scalability": 4, "complexity": 1, "serverless": True},
    {"id": "beanstalk", "title": "Elastic Beanstalk", "category": "Compute",
     "description": "PaaS that provisions EC2, ELB and Auto Scaling for you.",
     "tooltip": "Classic deploy of monolith web apps.",
     "difficulty": 1, "tags": ["web", "paas", "beginner"],
     "cost": 3, "security": 3, "scalability": 3, "complexity": 2, "serverless": False},

    # Storage (4)
    {"id": "s3", "title": "S3", "category": "Storage",
     "description": "Durable object storage. 11 nines of durability.",
     "tooltip": "Files, backups, static assets, data lakes.",
     "difficulty": 1, "tags": ["object", "files", "static", "data-lake", "durable"],
     "cost": 1, "security": 4, "scalability": 5, "complexity": 1, "serverless": True},
    {"id": "ebs", "title": "EBS", "category": "Storage",
     "description": "Block storage volumes for EC2.",
     "tooltip": "Disks for VMs. Snapshots for backup.",
     "difficulty": 2, "tags": ["block", "disk", "vm"],
     "cost": 3, "security": 3, "scalability": 2, "complexity": 2, "serverless": False},
    {"id": "efs", "title": "EFS", "category": "Storage",
     "description": "Shared NFS file system. Mount on many compute targets.",
     "tooltip": "Shared filesystem across multiple workers.",
     "difficulty": 2, "tags": ["file", "shared", "nfs"],
     "cost": 3, "security": 4, "scalability": 4, "complexity": 2, "serverless": True},
    {"id": "glacier", "title": "S3 Glacier", "category": "Storage",
     "description": "Archive-tier object storage. Pennies per GB.",
     "tooltip": "Long-term archive with retrieval delay.",
     "difficulty": 2, "tags": ["archive", "cheap", "backup"],
     "cost": 1, "security": 4, "scalability": 5, "complexity": 2, "serverless": True},

    # Database (5)
    {"id": "dynamodb", "title": "DynamoDB", "category": "Database",
     "description": "Serverless NoSQL key-value & document database.",
     "tooltip": "Low-latency single-digit ms reads, massive scale.",
     "difficulty": 2, "tags": ["nosql", "serverless", "scale", "low-latency"],
     "cost": 2, "security": 4, "scalability": 5, "complexity": 3, "serverless": True},
    {"id": "rds", "title": "RDS", "category": "Database",
     "description": "Managed relational databases (Postgres, MySQL, ...).",
     "tooltip": "Classic SQL when you need joins, transactions, schema.",
     "difficulty": 2, "tags": ["sql", "relational", "managed"],
     "cost": 3, "security": 4, "scalability": 3, "complexity": 3, "serverless": False},
    {"id": "aurora_serverless", "title": "Aurora Serverless", "category": "Database",
     "description": "MySQL/Postgres-compatible auto-scaling relational DB.",
     "tooltip": "SQL that scales with traffic. Pay for usage.",
     "difficulty": 3, "tags": ["sql", "serverless", "scale", "relational"],
     "cost": 3, "security": 4, "scalability": 5, "complexity": 3, "serverless": True},
    {"id": "elasticache", "title": "ElastiCache", "category": "Database",
     "description": "Managed Redis / Memcached for in-memory caching.",
     "tooltip": "Sub-millisecond reads. Session stores, leaderboards.",
     "difficulty": 2, "tags": ["cache", "low-latency", "redis"],
     "cost": 3, "security": 3, "scalability": 4, "complexity": 3, "serverless": False},
    {"id": "redshift", "title": "Redshift", "category": "Database",
     "description": "Petabyte-scale analytics data warehouse.",
     "tooltip": "OLAP queries on huge datasets.",
     "difficulty": 3, "tags": ["analytics", "warehouse", "olap"],
     "cost": 4, "security": 4, "scalability": 4, "complexity": 4, "serverless": False},

    # Network (5)
    {"id": "cloudfront", "title": "CloudFront", "category": "Network",
     "description": "Global CDN. Cache assets and APIs at the edge.",
     "tooltip": "Lower latency for global users. DDoS shield baked in.",
     "difficulty": 2, "tags": ["cdn", "edge", "low-latency", "static"],
     "cost": 2, "security": 4, "scalability": 5, "complexity": 2, "serverless": True},
    {"id": "route53", "title": "Route 53", "category": "Network",
     "description": "Authoritative DNS with health checks and failover.",
     "tooltip": "DNS-level routing and multi-region failover.",
     "difficulty": 2, "tags": ["dns", "failover", "ha"],
     "cost": 1, "security": 4, "scalability": 5, "complexity": 2, "serverless": True},
    {"id": "api_gateway", "title": "API Gateway", "category": "Network",
     "description": "Managed REST/HTTP/WebSocket front door for APIs.",
     "tooltip": "Auth, throttling, caching for your APIs.",
     "difficulty": 2, "tags": ["api", "rest", "serverless", "throttle"],
     "cost": 2, "security": 4, "scalability": 5, "complexity": 2, "serverless": True},
    {"id": "vpc", "title": "VPC", "category": "Network",
     "description": "Isolated virtual network. Subnets, route tables, gateways.",
     "tooltip": "Network boundary for your AWS resources.",
     "difficulty": 3, "tags": ["network", "isolation", "security"],
     "cost": 1, "security": 4, "scalability": 3, "complexity": 4, "serverless": False},
    {"id": "alb", "title": "ALB", "category": "Network",
     "description": "Application Load Balancer. Layer-7 traffic distribution.",
     "tooltip": "Path/host-based routing to many targets.",
     "difficulty": 2, "tags": ["load-balancer", "http", "ha"],
     "cost": 2, "security": 3, "scalability": 4, "complexity": 2, "serverless": False},

    # Security (5)
    {"id": "iam", "title": "IAM", "category": "Security",
     "description": "Identity and access management. Roles, policies, principals.",
     "tooltip": "Foundation of least-privilege access.",
     "difficulty": 2, "tags": ["auth", "roles", "least-privilege", "security"],
     "cost": 1, "security": 5, "scalability": 5, "complexity": 3, "serverless": True},
    {"id": "kms", "title": "KMS", "category": "Security",
     "description": "Managed encryption key service.",
     "tooltip": "Envelope encryption for data at rest.",
     "difficulty": 2, "tags": ["encryption", "keys", "security"],
     "cost": 1, "security": 5, "scalability": 5, "complexity": 2, "serverless": True},
    {"id": "waf", "title": "WAF", "category": "Security",
     "description": "Web Application Firewall in front of CloudFront / ALB / API GW.",
     "tooltip": "Block OWASP-class web attacks.",
     "difficulty": 2, "tags": ["firewall", "web", "security"],
     "cost": 2, "security": 5, "scalability": 5, "complexity": 2, "serverless": True},
    {"id": "cognito", "title": "Cognito", "category": "Security",
     "description": "User sign-up / sign-in & federated identity.",
     "tooltip": "Drop-in auth for web & mobile apps.",
     "difficulty": 2, "tags": ["auth", "users", "oauth", "security"],
     "cost": 1, "security": 5, "scalability": 5, "complexity": 3, "serverless": True},
    {"id": "secrets_manager", "title": "Secrets Manager", "category": "Security",
     "description": "Store, rotate and audit secrets.",
     "tooltip": "DB passwords, API keys, with automatic rotation.",
     "difficulty": 1, "tags": ["secrets", "rotation", "security"],
     "cost": 2, "security": 5, "scalability": 5, "complexity": 2, "serverless": True},

    # Analytics (2)
    {"id": "kinesis", "title": "Kinesis", "category": "Analytics",
     "description": "Real-time streaming data ingestion.",
     "tooltip": "Clickstreams, IoT, logs at scale.",
     "difficulty": 3, "tags": ["stream", "real-time", "data"],
     "cost": 3, "security": 4, "scalability": 5, "complexity": 4, "serverless": False},
    {"id": "athena", "title": "Athena", "category": "Analytics",
     "description": "Serverless SQL over data in S3.",
     "tooltip": "Query data-lake files without a cluster.",
     "difficulty": 2, "tags": ["sql", "serverless", "data-lake", "analytics"],
     "cost": 2, "security": 4, "scalability": 5, "complexity": 2, "serverless": True},

    # Integration (3)
    {"id": "sns", "title": "SNS", "category": "Integration",
     "description": "Pub/Sub messaging fan-out.",
     "tooltip": "Push notifications, fan-out to many subscribers.",
     "difficulty": 1, "tags": ["pubsub", "messaging", "serverless"],
     "cost": 1, "security": 4, "scalability": 5, "complexity": 1, "serverless": True},
    {"id": "sqs", "title": "SQS", "category": "Integration",
     "description": "Durable message queue.",
     "tooltip": "Decouple producers from consumers. Retry friendly.",
     "difficulty": 1, "tags": ["queue", "messaging", "serverless", "decouple"],
     "cost": 1, "security": 4, "scalability": 5, "complexity": 1, "serverless": True},
    {"id": "eventbridge", "title": "EventBridge", "category": "Integration",
     "description": "Event bus with SaaS and AWS integrations.",
     "tooltip": "Route events between services with filtering rules.",
     "difficulty": 2, "tags": ["event", "bus", "serverless", "integration"],
     "cost": 1, "security": 4, "scalability": 5, "complexity": 2, "serverless": True},

    # Monitoring (1)
    {"id": "cloudwatch", "title": "CloudWatch", "category": "Monitoring",
     "description": "Metrics, logs, alarms, dashboards.",
     "tooltip": "Default observability layer in AWS.",
     "difficulty": 2, "tags": ["metrics", "logs", "alarms", "observability"],
     "cost": 2, "security": 4, "scalability": 5, "complexity": 2, "serverless": True},
]

# 10 scenarios. ideal_tags / ideal_categories drive service-fit scoring.
# ideal_constraint_match indicates which constraint chips would naturally apply.
SCENARIOS = [
    {"id": "photo_sharing", "title": "Global Photo Sharing App",
     "prompt": "Users upload photos from their phone. Friends across the world view them. Expect viral spikes.",
     "ideal_categories": ["Storage", "Network", "Compute", "Database"],
     "ideal_tags": ["object", "cdn", "serverless", "scale", "low-latency"],
     "min_services": 3, "max_services": 6, "difficulty": 1},
    {"id": "fintech_api", "title": "Fintech Transactions API",
     "prompt": "REST API that records financial transactions. Strong auth, full audit trail, regional failover.",
     "ideal_categories": ["Network", "Database", "Security", "Compute"],
     "ideal_tags": ["api", "sql", "relational", "auth", "encryption", "secrets", "observability"],
     "min_services": 4, "max_services": 6, "difficulty": 3},
    {"id": "iot_telemetry", "title": "IoT Telemetry Pipeline",
     "prompt": "Millions of sensors push readings every second. Analysts query the data later.",
     "ideal_categories": ["Analytics", "Storage", "Compute", "Database"],
     "ideal_tags": ["stream", "real-time", "data-lake", "analytics", "object"],
     "min_services": 3, "max_services": 6, "difficulty": 2},
    {"id": "static_blog", "title": "Personal Static Blog",
     "prompt": "Mostly static pages. Few visitors. Cheap and simple.",
     "ideal_categories": ["Storage", "Network"],
     "ideal_tags": ["static", "cdn", "object", "beginner"],
     "min_services": 3, "max_services": 4, "difficulty": 1},
    {"id": "chat_app", "title": "Real-time Chat App",
     "prompt": "Low-latency messaging with presence, push notifications, and message history.",
     "ideal_categories": ["Network", "Database", "Compute", "Integration"],
     "ideal_tags": ["api", "low-latency", "messaging", "nosql", "pubsub"],
     "min_services": 4, "max_services": 6, "difficulty": 2},
    {"id": "ecommerce", "title": "E-commerce Storefront",
     "prompt": "Product catalog, cart, checkout, order processing. Holiday spikes.",
     "ideal_categories": ["Compute", "Database", "Network", "Integration", "Security"],
     "ideal_tags": ["web", "sql", "relational", "queue", "auth", "scale", "cdn"],
     "min_services": 4, "max_services": 6, "difficulty": 2},
    {"id": "ml_batch", "title": "Nightly ML Training",
     "prompt": "Each night, retrain a model on yesterday's data, then archive the result.",
     "ideal_categories": ["Storage", "Compute", "Analytics"],
     "ideal_tags": ["data-lake", "archive", "vm", "container"],
     "min_services": 3, "max_services": 5, "difficulty": 3},
    {"id": "internal_dashboard", "title": "Internal Analytics Dashboard",
     "prompt": "Business users explore last quarter's data via SQL. Read-only. Tens of analysts.",
     "ideal_categories": ["Analytics", "Storage", "Database", "Security"],
     "ideal_tags": ["analytics", "warehouse", "data-lake", "sql", "auth"],
     "min_services": 3, "max_services": 5, "difficulty": 2},
    {"id": "gaming_leaderboard", "title": "Mobile Game Leaderboard",
     "prompt": "Top-1000 scoreboard updated every few seconds. Millions of players globally.",
     "ideal_categories": ["Database", "Compute", "Network"],
     "ideal_tags": ["cache", "low-latency", "redis", "nosql", "api", "serverless"],
     "min_services": 3, "max_services": 5, "difficulty": 2},
    {"id": "compliance_logs", "title": "Compliance Log Archive",
     "prompt": "Store and never lose audit logs. Retain 7 years. Read once a year.",
     "ideal_categories": ["Storage", "Security", "Monitoring"],
     "ideal_tags": ["archive", "object", "encryption", "logs", "observability"],
     "min_services": 3, "max_services": 4, "difficulty": 1},
]

# Service pairs that work great together — used for synergy bonus.
SYNERGIES = [
    ("lambda", "api_gateway"),
    ("lambda", "dynamodb"),
    ("lambda", "s3"),
    ("lambda", "sqs"),
    ("lambda", "sns"),
    ("lambda", "eventbridge"),
    ("s3", "cloudfront"),
    ("s3", "athena"),
    ("ec2", "rds"),
    ("ec2", "ebs"),
    ("ec2", "alb"),
    ("ecs_fargate", "alb"),
    ("api_gateway", "cognito"),
    ("api_gateway", "waf"),
    ("cloudfront", "waf"),
    ("cloudfront", "route53"),
    ("kinesis", "s3"),
    ("kinesis", "lambda"),
    ("rds", "elasticache"),
    ("dynamodb", "api_gateway"),
    ("redshift", "s3"),
    ("athena", "s3"),
    ("cloudwatch", "lambda"),
    ("cloudwatch", "ec2"),
    ("iam", "kms"),
    ("kms", "s3"),
    ("kms", "rds"),
    ("secrets_manager", "rds"),
    ("cognito", "api_gateway"),
]
