"""
Seed data for AWS CloudForge Cards.
Adding more cards later: append to SERVICE_CARDS / SCENARIOS / CONSTRAINTS.
Each service card has:
  - cost / security / scalability / complexity rated 1-5
  - serverless flag
  - tags (free-form keywords used by the scoring engine for ideal-fit matching)
"""

CONSTRAINTS = [
    {"id": "low_cost", "name": "Low Cost", "color": "yellow",
     "description": "Minimize spend. Prefer pay-per-use, free tiers, lean footprint."},
    {"id": "high_availability", "name": "High Availability", "color": "blue",
     "description": "Survive zone/region failures. Replicas, multi-AZ, failover."},
    {"id": "serverless", "name": "Serverless", "color": "green",
     "description": "No servers to manage. Auto-scaling, event driven."},
    {"id": "secure", "name": "Secure", "color": "red",
     "description": "Strong auth, encryption, least privilege, audit trails."},
    {"id": "scalable", "name": "Scalable", "color": "blue",
     "description": "Handle 10x or 1000x traffic gracefully."},
    {"id": "beginner_friendly", "name": "Beginner Friendly", "color": "green",
     "description": "Low operational complexity. Easy to learn and operate."},
    {"id": "low_latency", "name": "Low Latency", "color": "yellow",
     "description": "Sub-100ms response. Caching, edge, in-memory layers."},
    {"id": "observability", "name": "Observability", "color": "blue",
     "description": "Logs, metrics, traces. Know what is happening in prod."},
]

# 30 service cards, categories: Compute, Storage, Database, Network, Security, Analytics, Integration, Monitoring
SERVICE_CARDS = [
    # Compute (6)
    {"id": "lambda", "title": "Lambda", "category": "Compute",
     "description": "Run code without provisioning servers. Pay per ms of execution.",
     "tooltip": "Best for event-driven workloads, short tasks, glue between services.",
     "difficulty": 1, "tags": ["serverless", "event", "api", "glue", "scale"],
     "cost": 1, "security": 4, "scalability": 5, "complexity": 2, "serverless": True},
    {"id": "ec2", "title": "EC2", "category": "Compute",
     "description": "Virtual machines in the cloud. Full OS control.",
     "tooltip": "Use when you need stateful workloads or custom OS.",
     "difficulty": 2, "tags": ["vm", "compute", "stateful"],
     "cost": 4, "security": 3, "scalability": 3, "complexity": 3, "serverless": False},
    {"id": "ecs_fargate", "title": "ECS on Fargate", "category": "Compute",
     "description": "Run containers without managing servers.",
     "tooltip": "Container workloads with no node management.",
     "difficulty": 2, "tags": ["container", "serverless", "scale"],
     "cost": 3, "security": 4, "scalability": 4, "complexity": 3, "serverless": True},
    {"id": "ecs_ec2", "title": "ECS on EC2", "category": "Compute",
     "description": "Container orchestration on managed EC2 nodes.",
     "tooltip": "Containers where you control the host.",
     "difficulty": 3, "tags": ["container", "cluster"],
     "cost": 3, "security": 3, "scalability": 4, "complexity": 4, "serverless": False},
    {"id": "app_runner", "title": "App Runner", "category": "Compute",
     "description": "Deploy web apps from source or container with zero infra.",
     "tooltip": "Fastest way to ship a containerized web service.",
     "difficulty": 1, "tags": ["web", "container", "beginner", "serverless"],
     "cost": 3, "security": 4, "scalability": 4, "complexity": 1, "serverless": True},
    {"id": "beanstalk", "title": "Elastic Beanstalk", "category": "Compute",
     "description": "PaaS that provisions EC2, ELB and Auto Scaling for you.",
     "tooltip": "Classic deploy of monolith web apps.",
     "difficulty": 1, "tags": ["web", "paas", "beginner"],
     "cost": 3, "security": 3, "scalability": 3, "complexity": 2, "serverless": False},

    # Storage (4)
    {"id": "s3", "title": "S3", "category": "Storage",
     "description": "Durable object storage. 11 nines of durability.",
     "tooltip": "Files, backups, static assets, data lakes.",
     "difficulty": 1, "tags": ["object", "files", "static", "data-lake", "durable"],
     "cost": 1, "security": 4, "scalability": 5, "complexity": 1, "serverless": True},
    {"id": "ebs", "title": "EBS", "category": "Storage",
     "description": "Block storage volumes for EC2.",
     "tooltip": "Disks for VMs. Snapshots for backup.",
     "difficulty": 2, "tags": ["block", "disk", "vm"],
     "cost": 3, "security": 3, "scalability": 2, "complexity": 2, "serverless": False},
    {"id": "efs", "title": "EFS", "category": "Storage",
     "description": "Shared NFS file system. Mount on many compute targets.",
     "tooltip": "Shared filesystem across multiple workers.",
     "difficulty": 2, "tags": ["file", "shared", "nfs"],
     "cost": 3, "security": 4, "scalability": 4, "complexity": 2, "serverless": True},
    {"id": "glacier", "title": "S3 Glacier", "category": "Storage",
     "description": "Archive-tier object storage. Pennies per GB.",
     "tooltip": "Long-term archive with retrieval delay.",
     "difficulty": 2, "tags": ["archive", "cheap", "backup"],
     "cost": 1, "security": 4, "scalability": 5, "complexity": 2, "serverless": True},

    # Database (5)
    {"id": "dynamodb", "title": "DynamoDB", "category": "Database",
     "description": "Serverless NoSQL key-value & document database.",
     "tooltip": "Low-latency single-digit ms reads, massive scale.",
     "difficulty": 2, "tags": ["nosql", "serverless", "scale", "low-latency"],
     "cost": 2, "security": 4, "scalability": 5, "complexity": 3, "serverless": True},
    {"id": "rds", "title": "RDS", "category": "Database",
     "description": "Managed relational databases (Postgres, MySQL, ...).",
     "tooltip": "Classic SQL when you need joins, transactions, schema.",
     "difficulty": 2, "tags": ["sql", "relational", "managed"],
     "cost": 3, "security": 4, "scalability": 3, "complexity": 3, "serverless": False},
    {"id": "aurora_serverless", "title": "Aurora Serverless", "category": "Database",
     "description": "MySQL/Postgres-compatible auto-scaling relational DB.",
     "tooltip": "SQL that scales with traffic. Pay for usage.",
     "difficulty": 3, "tags": ["sql", "serverless", "scale", "relational"],
     "cost": 3, "security": 4, "scalability": 5, "complexity": 3, "serverless": True},
    {"id": "elasticache", "title": "ElastiCache", "category": "Database",
     "description": "Managed Redis / Memcached for in-memory caching.",
     "tooltip": "Sub-millisecond reads. Session stores, leaderboards.",
     "difficulty": 2, "tags": ["cache", "low-latency", "redis"],
     "cost": 3, "security": 3, "scalability": 4, "complexity": 3, "serverless": False},
    {"id": "redshift", "title": "Redshift", "category": "Database",
     "description": "Petabyte-scale analytics data warehouse.",
     "tooltip": "OLAP queries on huge datasets.",
     "difficulty": 3, "tags": ["analytics", "warehouse", "olap"],
     "cost": 4, "security": 4, "scalability": 4, "complexity": 4, "serverless": False},

    # Network (5)
    {"id": "cloudfront", "title": "CloudFront", "category": "Network",
     "description": "Global CDN. Cache assets and APIs at the edge.",
     "tooltip": "Lower latency for global users. DDoS shield baked in.",
     "difficulty": 2, "tags": ["cdn", "edge", "low-latency", "static"],
     "cost": 2, "security": 4, "scalability": 5, "complexity": 2, "serverless": True},
    {"id": "route53", "title": "Route 53", "category": "Network",
     "description": "Authoritative DNS with health checks and failover.",
     "tooltip": "DNS-level routing and multi-region failover.",
     "difficulty": 2, "tags": ["dns", "failover", "ha"],
     "cost": 1, "security": 4, "scalability": 5, "complexity": 2, "serverless": True},
    {"id": "api_gateway", "title": "API Gateway", "category": "Network",
     "description": "Managed REST/HTTP/WebSocket front door for APIs.",
     "tooltip": "Auth, throttling, caching for your APIs.",
     "difficulty": 2, "tags": ["api", "rest", "serverless", "throttle"],
     "cost": 2, "security": 4, "scalability": 5, "complexity": 2, "serverless": True},
    {"id": "vpc", "title": "VPC", "category": "Network",
     "description": "Isolated virtual network. Subnets, route tables, gateways.",
     "tooltip": "Network boundary for your AWS resources.",
     "difficulty": 3, "tags": ["network", "isolation", "security"],
     "cost": 1, "security": 4, "scalability": 3, "complexity": 4, "serverless": False},
    {"id": "alb", "title": "ALB", "category": "Network",
     "description": "Application Load Balancer. Layer-7 traffic distribution.",
     "tooltip": "Path/host-based routing to many targets.",
     "difficulty": 2, "tags": ["load-balancer", "http", "ha"],
     "cost": 2, "security": 3, "scalability": 4, "complexity": 2, "serverless": False},

    # Security (5)
    {"id": "iam", "title": "IAM", "category": "Security",
     "description": "Identity and access management. Roles, policies, principals.",
     "tooltip": "Foundation of least-privilege access.",
     "difficulty": 2, "tags": ["auth", "roles", "least-privilege", "security"],
     "cost": 1, "security": 5, "scalability": 5, "complexity": 3, "serverless": True},
    {"id": "kms", "title": "KMS", "category": "Security",
     "description": "Managed encryption key service.",
     "tooltip": "Envelope encryption for data at rest.",
     "difficulty": 2, "tags": ["encryption", "keys", "security"],
     "cost": 1, "security": 5, "scalability": 5, "complexity": 2, "serverless": True},
    {"id": "waf", "title": "WAF", "category": "Security",
     "description": "Web Application Firewall in front of CloudFront / ALB / API GW.",
     "tooltip": "Block OWASP-class web attacks.",
     "difficulty": 2, "tags": ["firewall", "web", "security"],
     "cost": 2, "security": 5, "scalability": 5, "complexity": 2, "serverless": True},
    {"id": "cognito", "title": "Cognito", "category": "Security",
     "description": "User sign-up / sign-in & federated identity.",
     "tooltip": "Drop-in auth for web & mobile apps.",
     "difficulty": 2, "tags": ["auth", "users", "oauth", "security"],
     "cost": 1, "security": 5, "scalability": 5, "complexity": 3, "serverless": True},
    {"id": "secrets_manager", "title": "Secrets Manager", "category": "Security",
     "description": "Store, rotate and audit secrets.",
     "tooltip": "DB passwords, API keys, with automatic rotation.",
     "difficulty": 1, "tags": ["secrets", "rotation", "security"],
     "cost": 2, "security": 5, "scalability": 5, "complexity": 2, "serverless": True},

    # Analytics (2)
    {"id": "kinesis", "title": "Kinesis", "category": "Analytics",
     "description": "Real-time streaming data ingestion.",
     "tooltip": "Clickstreams, IoT, logs at scale.",
     "difficulty": 3, "tags": ["stream", "real-time", "data"],
     "cost": 3, "security": 4, "scalability": 5, "complexity": 4, "serverless": False},
    {"id": "athena", "title": "Athena", "category": "Analytics",
     "description": "Serverless SQL over data in S3.",
     "tooltip": "Query data-lake files without a cluster.",
     "difficulty": 2, "tags": ["sql", "serverless", "data-lake", "analytics"],
     "cost": 2, "security": 4, "scalability": 5, "complexity": 2, "serverless": True},
    {"id": "glue_catalog", "title": "Glue Data Catalog", "category": "Analytics",
     "description": "Central metadata catalog for data lakes. Holds schemas & table definitions for Athena/Redshift.",
     "tooltip": "Crawl S3, register schemas, power serverless SQL queries with consistent metadata.",
     "difficulty": 2, "tags": ["data-catalog", "metadata", "serverless", "analytics", "data-lake"],
     "cost": 1, "security": 4, "scalability": 5, "complexity": 2, "serverless": True},

    # Integration (3)
    {"id": "sns", "title": "SNS", "category": "Integration",
     "description": "Pub/Sub messaging fan-out.",
     "tooltip": "Push notifications, fan-out to many subscribers.",
     "difficulty": 1, "tags": ["pubsub", "messaging", "serverless"],
     "cost": 1, "security": 4, "scalability": 5, "complexity": 1, "serverless": True},
    {"id": "sqs", "title": "SQS", "category": "Integration",
     "description": "Durable message queue.",
     "tooltip": "Decouple producers from consumers. Retry friendly.",
     "difficulty": 1, "tags": ["queue", "messaging", "serverless", "decouple"],
     "cost": 1, "security": 4, "scalability": 5, "complexity": 1, "serverless": True},
    {"id": "eventbridge", "title": "EventBridge", "category": "Integration",
     "description": "Event bus with SaaS and AWS integrations.",
     "tooltip": "Route events between services with filtering rules.",
     "difficulty": 2, "tags": ["event", "bus", "serverless", "integration"],
     "cost": 1, "security": 4, "scalability": 5, "complexity": 2, "serverless": True},

    # Monitoring (1)
    {"id": "cloudwatch", "title": "CloudWatch", "category": "Monitoring",
     "description": "Metrics, logs, alarms, dashboards.",
     "tooltip": "Default observability layer in AWS.",
     "difficulty": 2, "tags": ["metrics", "logs", "alarms", "observability"],
     "cost": 2, "security": 4, "scalability": 5, "complexity": 2, "serverless": True},

    # AI (2)
    {"id": "bedrock", "title": "Bedrock", "category": "AI",
     "description": "Managed access to foundation models (Claude, Llama, Titan).",
     "tooltip": "Drop-in LLM/embedding APIs without provisioning GPUs.",
     "difficulty": 2, "tags": ["llm", "genai", "serverless", "ai"],
     "cost": 3, "security": 4, "scalability": 5, "complexity": 2, "serverless": True},
    {"id": "sagemaker", "title": "SageMaker", "category": "AI",
     "description": "End-to-end ML platform: train, tune, deploy models.",
     "tooltip": "Train custom models or deploy them as endpoints.",
     "difficulty": 3, "tags": ["ml", "train", "ai", "endpoint"],
     "cost": 4, "security": 4, "scalability": 4, "complexity": 4, "serverless": False},
]

# 10 scenarios. ideal_tags / ideal_categories drive service-fit scoring.
# ideal_constraint_match indicates which constraint chips would naturally apply.
SCENARIOS = [
    {"id": "photo_sharing", "hint": {"text":'Photos are large files served globally. Think about object storage and edge caching first.', "kw":["object storage", "low latency", "serverless"]}, "title": "Global Photo Sharing App",
     "prompt": "Users upload photos from their phone. Friends across the world view them. Expect viral spikes.",
     "ideal_categories": ["Storage", "Network", "Compute", "Database"],
     "ideal_tags": ["object", "cdn", "serverless", "scale", "low-latency"],
     "min_services": 3, "max_services": 6, "difficulty": 1,
     "core_service_ids": ["s3", "cloudfront", "lambda", "dynamodb"],
     "supporting_service_ids": ["api_gateway", "route53", "cognito", "cloudwatch", "sns"],
     "distractor_service_ids": ["ec2", "rds", "redshift", "kinesis", "sagemaker", "glacier", "ebs", "beanstalk"],
     "ideal_combos": [["s3", "cloudfront", "lambda", "dynamodb"],
                      ["s3", "cloudfront", "api_gateway", "lambda", "dynamodb"]]},
    {"id": "fintech_api", "hint": {"text":'Money moves through this API. Prioritize authentication, encryption, and a relational store.', "kw":["SQL", "authentication", "encryption"]}, "title": "Fintech Transactions API",
     "prompt": "REST API that records financial transactions. Strong auth, full audit trail, regional failover.",
     "ideal_categories": ["Network", "Database", "Security", "Compute"],
     "ideal_tags": ["api", "sql", "relational", "auth", "encryption", "secrets", "observability"],
     "min_services": 4, "max_services": 6, "difficulty": 3,
     "core_service_ids": ["api_gateway", "lambda", "rds", "aurora_serverless", "cognito", "secrets_manager", "kms"],
     "supporting_service_ids": ["waf", "cloudwatch", "iam", "dynamodb", "route53"],
     "distractor_service_ids": ["s3", "cloudfront", "kinesis", "sagemaker", "redshift", "glacier", "beanstalk"],
     "ideal_combos": [["api_gateway", "lambda", "rds", "cognito", "secrets_manager"],
                      ["api_gateway", "lambda", "aurora_serverless", "cognito", "kms"]]},
    {"id": "iot_telemetry", "hint": {"text":'Millions of small events per second land here. Stream first, then land in a data lake.', "kw":["streaming", "data catalog", "object storage"]}, "title": "IoT Telemetry Pipeline",
     "prompt": "Millions of sensors push readings every second. Analysts query the data later.",
     "ideal_categories": ["Analytics", "Storage", "Compute", "Database"],
     "ideal_tags": ["stream", "real-time", "data-lake", "analytics", "object"],
     "min_services": 3, "max_services": 6, "difficulty": 2,
     "core_service_ids": ["kinesis", "lambda", "s3", "athena", "dynamodb"],
     "supporting_service_ids": ["glue_catalog", "cloudwatch", "iam", "redshift"],
     "distractor_service_ids": ["rds", "cloudfront", "cognito", "beanstalk", "ec2", "sagemaker"],
     "ideal_combos": [["kinesis", "lambda", "s3", "athena"],
                      ["kinesis", "s3", "athena", "dynamodb"]]},
    {"id": "static_blog", "hint": {"text":'A blog with few visitors should be near-free. Static files + CDN beat a server every time.', "kw":["object storage", "low cost", "CDN"]}, "title": "Personal Static Blog",
     "prompt": "Mostly static pages. Few visitors. Cheap and simple.",
     "ideal_categories": ["Storage", "Network"],
     "ideal_tags": ["static", "cdn", "object", "beginner"],
     "min_services": 3, "max_services": 4, "difficulty": 1,
     "core_service_ids": ["s3", "cloudfront", "route53"],
     "supporting_service_ids": ["cloudwatch", "waf", "iam"],
     "distractor_service_ids": ["ec2", "rds", "lambda", "dynamodb", "kinesis", "redshift", "sagemaker", "ecs_fargate"],
     "ideal_combos": [["s3", "cloudfront", "route53"]]},
    {"id": "chat_app", "hint": {"text":'Latency is everything. Combine an event-driven backend with a fast key-value store.', "kw":["low latency", "event-driven", "caching"]}, "title": "Real-time Chat App",
     "prompt": "Low-latency messaging with presence, push notifications, and message history.",
     "ideal_categories": ["Network", "Database", "Compute", "Integration"],
     "ideal_tags": ["api", "low-latency", "messaging", "nosql", "pubsub"],
     "min_services": 4, "max_services": 6, "difficulty": 2,
     "core_service_ids": ["api_gateway", "lambda", "dynamodb", "sns", "elasticache"],
     "supporting_service_ids": ["cognito", "cloudwatch", "sqs", "eventbridge"],
     "distractor_service_ids": ["s3", "rds", "redshift", "kinesis", "ec2", "sagemaker", "glacier"],
     "ideal_combos": [["api_gateway", "lambda", "dynamodb", "sns"],
                      ["api_gateway", "lambda", "dynamodb", "elasticache"]]},
    {"id": "ecommerce", "hint": {"text":'Holiday spikes break monoliths. Decouple checkout with a queue and protect with a CDN.', "kw":["scalable", "queue", "CDN"]}, "title": "E-commerce Storefront",
     "prompt": "Product catalog, cart, checkout, order processing. Holiday spikes.",
     "ideal_categories": ["Compute", "Database", "Network", "Integration", "Security"],
     "ideal_tags": ["web", "sql", "relational", "queue", "auth", "scale", "cdn"],
     "min_services": 4, "max_services": 6, "difficulty": 2,
     "core_service_ids": ["cloudfront", "alb", "ecs_fargate", "rds", "sqs", "api_gateway", "lambda", "dynamodb"],
     "supporting_service_ids": ["cognito", "waf", "cloudwatch", "elasticache", "route53"],
     "distractor_service_ids": ["kinesis", "redshift", "sagemaker", "glacier", "athena"],
     "ideal_combos": [["cloudfront", "alb", "ecs_fargate", "rds", "sqs"],
                      ["cloudfront", "api_gateway", "lambda", "dynamodb", "sqs"]]},
    {"id": "ml_batch", "hint": {"text":'A nightly job means batch compute on a data lake, not always-on infrastructure.', "kw":["historical data", "object storage", "batch"]}, "title": "Nightly ML Training",
     "prompt": "Each night, retrain a model on yesterday's data, then archive the result.",
     "ideal_categories": ["Storage", "Compute", "Analytics", "AI"],
     "ideal_tags": ["data-lake", "archive", "vm", "container", "ml", "train"],
     "min_services": 3, "max_services": 5, "difficulty": 3,
     "core_service_ids": ["s3", "sagemaker", "glacier", "ecs_fargate", "athena"],
     "supporting_service_ids": ["glue_catalog", "cloudwatch", "iam", "ec2", "bedrock"],
     "distractor_service_ids": ["cloudfront", "route53", "cognito", "dynamodb", "api_gateway", "sns"],
     "ideal_combos": [["s3", "sagemaker", "glacier"],
                      ["s3", "ecs_fargate", "athena", "glacier"]]},
    {"id": "internal_dashboard", "hint": {"text":'Read-only analysts querying historical data. Think warehouse + SQL on a lake.', "kw":["SQL", "historical data", "read-only access"]}, "title": "Internal Analytics Dashboard",
     "prompt": "Business users explore last quarter's data via SQL. Read-only. Tens of analysts.",
     "ideal_categories": ["Analytics", "Storage", "Database", "Security"],
     "ideal_tags": ["analytics", "warehouse", "data-lake", "sql", "auth"],
     "min_services": 3, "max_services": 5, "difficulty": 2,
     "core_service_ids": ["s3", "athena", "redshift"],
     "supporting_service_ids": ["glue_catalog", "cognito", "iam", "cloudwatch"],
     "distractor_service_ids": ["kinesis", "lambda", "sns", "sqs", "ec2", "sagemaker", "cloudfront", "route53"],
     "ideal_combos": [["s3", "athena", "redshift", "cognito"],
                      ["s3", "athena", "redshift", "iam"],
                      ["s3", "athena", "glue_catalog", "iam"]]},
    {"id": "gaming_leaderboard", "hint": {"text":'Top-1000 changes constantly. Use a cache in front of a low-latency NoSQL store.', "kw":["caching", "low latency", "serverless"]}, "title": "Mobile Game Leaderboard",
     "prompt": "Top-1000 scoreboard updated every few seconds. Millions of players globally.",
     "ideal_categories": ["Database", "Compute", "Network"],
     "ideal_tags": ["cache", "low-latency", "redis", "nosql", "api", "serverless"],
     "min_services": 3, "max_services": 5, "difficulty": 2,
     "core_service_ids": ["api_gateway", "lambda", "elasticache", "dynamodb", "cloudfront"],
     "supporting_service_ids": ["route53", "cloudwatch", "sns", "cognito"],
     "distractor_service_ids": ["rds", "redshift", "kinesis", "s3", "sagemaker", "glacier"],
     "ideal_combos": [["api_gateway", "lambda", "elasticache", "dynamodb"],
                      ["api_gateway", "lambda", "dynamodb", "cloudfront"]]},
    {"id": "compliance_logs", "hint": {"text":'Write once, read rarely, keep 7 years. Archive storage with strict key management.', "kw":["object storage", "archive", "encryption"]}, "title": "Compliance Log Archive",
     "prompt": "Store and never lose audit logs. Retain 7 years. Read once a year.",
     "ideal_categories": ["Storage", "Security", "Monitoring"],
     "ideal_tags": ["archive", "object", "encryption", "logs", "observability"],
     "min_services": 3, "max_services": 4, "difficulty": 1,
     "core_service_ids": ["s3", "glacier", "cloudwatch", "kms", "iam"],
     "supporting_service_ids": ["secrets_manager", "waf"],
     "distractor_service_ids": ["ec2", "lambda", "dynamodb", "kinesis", "redshift", "sagemaker", "cloudfront"],
     "ideal_combos": [["s3", "glacier", "cloudwatch", "kms"],
                      ["s3", "glacier", "kms", "iam"]]},
]

# Service pairs that work great together, used for synergy bonus.
SYNERGIES = [
    ("lambda", "api_gateway"),
    ("lambda", "dynamodb"),
    ("lambda", "s3"),
    ("lambda", "sqs"),
    ("lambda", "sns"),
    ("lambda", "eventbridge"),
    ("s3", "cloudfront"),
    ("s3", "athena"),
    ("ec2", "rds"),
    ("ec2", "ebs"),
    ("ec2", "alb"),
    ("ecs_fargate", "alb"),
    ("api_gateway", "cognito"),
    ("api_gateway", "waf"),
    ("cloudfront", "waf"),
    ("cloudfront", "route53"),
    ("kinesis", "s3"),
    ("kinesis", "lambda"),
    ("rds", "elasticache"),
    ("dynamodb", "api_gateway"),
    ("redshift", "s3"),
    ("athena", "s3"),
    ("cloudwatch", "lambda"),
    ("cloudwatch", "ec2"),
    ("iam", "kms"),
    ("kms", "s3"),
    ("kms", "rds"),
    ("secrets_manager", "rds"),
    ("cognito", "api_gateway"),
    ("sagemaker", "s3"),
    ("bedrock", "lambda"),
    ("bedrock", "api_gateway"),
    ("glue_catalog", "athena"),
    ("glue_catalog", "s3"),
    ("glue_catalog", "redshift"),
]

# ---------- v0.4.2 Phase 5C: track-aware Play expansion ----------
from play_expansion import (
    EXPANSION_CARDS, EXPANSION_SCENARIOS, EXPANSION_SYNERGIES,
    BASE_CARD_TRACKS, BASE_SCENARIO_TRACKS, DEFAULT_CARD_TRACK,
)

# Tag base cards and scenarios with certification tracks. Every base card and
# scenario keeps CLF_SAA, so existing CLF/SAA Play behavior is unchanged.
for _card in SERVICE_CARDS:
    _card["tracks"] = BASE_CARD_TRACKS.get(_card["id"], [DEFAULT_CARD_TRACK])
for _scenario in SCENARIOS:
    _scenario["tracks"] = BASE_SCENARIO_TRACKS.get(_scenario["id"], ["CLF_SAA"])

SERVICE_CARDS.extend(EXPANSION_CARDS)
SCENARIOS.extend(EXPANSION_SCENARIOS)
SYNERGIES.extend(EXPANSION_SYNERGIES)

PLAY_TRACKS = ["CLF_SAA", "AIF", "MLA", "DEA", "MIXED"]


def scenarios_for_track(track):
    """Play scenario pool for a track. MIXED and unknown tracks return all."""
    t = (track or "MIXED").upper()
    if t == "MIXED":
        return SCENARIOS
    scoped = [s for s in SCENARIOS if t in s.get("tracks", [])]
    return scoped or SCENARIOS


def cards_for_track(track):
    """Service card pool for a track. MIXED and unknown tracks return all."""
    t = (track or "MIXED").upper()
    if t == "MIXED":
        return SERVICE_CARDS
    scoped = [c for c in SERVICE_CARDS if t in c.get("tracks", [])]
    return scoped or SERVICE_CARDS

