"""
v0.3 Phase 2 - Test Mode question bank and SERVER-SIDE grading.

Answer keys (`correct`) never leave this module: session responses are sanitized to
strip `correct`, and grading happens here. No user quiz history is stored.

Question shape:
  question_id, prompt, question_type ("mcq" | "truefalse" | "scenario_select"),
  answer_options [{id, text}], correct [option ids], explanation, exam_tracks[],
  domains[], related_services[], difficulty (1-3), professor_flock_hint
"""
import random
from typing import List, Dict, Any

SESSION_SIZE = 15

_TF = [{"id": "true", "text": "True"}, {"id": "false", "text": "False"}]


def _svc(*pairs):
    return [{"id": i, "text": t} for i, t in pairs]


QUESTIONS: List[Dict[str, Any]] = [
    # ---------------- CLF / SAA ----------------
    {"question_id": "clf_01", "prompt": "Which AWS service provides durable object storage for files, media, and data lakes?",
     "question_type": "mcq",
     "answer_options": [{"id": "a", "text": "Amazon S3"}, {"id": "b", "text": "Amazon EBS"}, {"id": "c", "text": "Amazon RDS"}, {"id": "d", "text": "Amazon Redshift"}],
     "correct": ["a"], "explanation": "S3 is object storage and the backbone of most architectures and data lakes.",
     "exam_tracks": ["CLF_SAA"], "domains": ["Storage"], "related_services": ["s3"], "difficulty": 1,
     "professor_flock_hint": "Think buckets and objects, not disks or tables."},
    {"question_id": "clf_02", "prompt": "Which service caches content at edge locations to deliver it with low latency worldwide?",
     "question_type": "mcq",
     "answer_options": [{"id": "a", "text": "Route 53"}, {"id": "b", "text": "CloudFront"}, {"id": "c", "text": "API Gateway"}, {"id": "d", "text": "ALB"}],
     "correct": ["b"], "explanation": "CloudFront is the CDN that caches at the edge close to users.",
     "exam_tracks": ["CLF_SAA"], "domains": ["Networking"], "related_services": ["cloudfront"], "difficulty": 1,
     "professor_flock_hint": "Edge locations are the giveaway."},
    {"question_id": "clf_03", "prompt": "Lambda is the best choice for long-running, always-on compute workloads.",
     "question_type": "truefalse", "answer_options": _TF, "correct": ["false"],
     "explanation": "Lambda suits short, event-driven work. Long-running or always-on jobs fit containers or EC2.",
     "exam_tracks": ["CLF_SAA"], "domains": ["Compute"], "related_services": ["lambda", "ec2", "ecs_fargate"], "difficulty": 1,
     "professor_flock_hint": "Lambda functions are short-lived by design."},
    {"question_id": "clf_04", "prompt": "Which service is a managed relational SQL database with joins and transactions?",
     "question_type": "mcq",
     "answer_options": [{"id": "a", "text": "DynamoDB"}, {"id": "b", "text": "ElastiCache"}, {"id": "c", "text": "Amazon RDS"}, {"id": "d", "text": "Amazon S3"}],
     "correct": ["c"], "explanation": "RDS is managed relational SQL. DynamoDB is NoSQL.",
     "exam_tracks": ["CLF_SAA"], "domains": ["Databases"], "related_services": ["rds"], "difficulty": 1,
     "professor_flock_hint": "Joins and transactions mean relational."},
    {"question_id": "clf_05", "prompt": "Which service is serverless NoSQL with single-digit millisecond reads at any scale?",
     "question_type": "mcq",
     "answer_options": [{"id": "a", "text": "Amazon RDS"}, {"id": "b", "text": "DynamoDB"}, {"id": "c", "text": "Redshift"}, {"id": "d", "text": "Athena"}],
     "correct": ["b"], "explanation": "DynamoDB is serverless NoSQL built for massive scale and low latency.",
     "exam_tracks": ["CLF_SAA"], "domains": ["Databases"], "related_services": ["dynamodb"], "difficulty": 1,
     "professor_flock_hint": "Key-value at web scale."},
    {"question_id": "clf_06", "prompt": "Pick the services for the cheapest, simplest static website with a custom domain.",
     "question_type": "scenario_select",
     "answer_options": _svc(("s3", "Amazon S3"), ("cloudfront", "CloudFront"), ("route53", "Route 53"), ("ec2", "Amazon EC2"), ("rds", "Amazon RDS")),
     "correct": ["s3", "cloudfront", "route53"], "explanation": "Static files in S3, cached by CloudFront, with Route 53 DNS. No servers needed.",
     "exam_tracks": ["CLF_SAA"], "domains": ["Storage", "Networking"], "related_services": ["s3", "cloudfront", "route53"], "difficulty": 2,
     "professor_flock_hint": "No servers for static content. Object storage plus CDN plus DNS."},
    {"question_id": "clf_07", "prompt": "Route 53 is the AWS Domain Name System (DNS) service.",
     "question_type": "truefalse", "answer_options": _TF, "correct": ["true"],
     "explanation": "Route 53 provides DNS, health checks, and routing policies.",
     "exam_tracks": ["CLF_SAA"], "domains": ["Networking"], "related_services": ["route53"], "difficulty": 1,
     "professor_flock_hint": "The number 53 is the DNS port."},
    {"question_id": "clf_08", "prompt": "Which service is a durable queue used to decouple producers from consumers?",
     "question_type": "mcq",
     "answer_options": [{"id": "a", "text": "SNS"}, {"id": "b", "text": "SQS"}, {"id": "c", "text": "Kinesis"}, {"id": "d", "text": "EventBridge"}],
     "correct": ["b"], "explanation": "SQS is a durable queue. SNS is pub/sub fan-out.",
     "exam_tracks": ["CLF_SAA"], "domains": ["Integration"], "related_services": ["sqs"], "difficulty": 2,
     "professor_flock_hint": "Queue means buffer and decouple."},
    {"question_id": "clf_09", "prompt": "Which service is pub/sub messaging that fans one message out to many subscribers?",
     "question_type": "mcq",
     "answer_options": [{"id": "a", "text": "SQS"}, {"id": "b", "text": "SNS"}, {"id": "c", "text": "RDS"}, {"id": "d", "text": "S3"}],
     "correct": ["b"], "explanation": "SNS fans out one message to many subscribers. SQS is a queue.",
     "exam_tracks": ["CLF_SAA"], "domains": ["Integration"], "related_services": ["sns"], "difficulty": 2,
     "professor_flock_hint": "Fan-out is the clue."},
    {"question_id": "clf_10", "prompt": "Which service provides an in-memory cache to speed up read-heavy workloads?",
     "question_type": "mcq",
     "answer_options": [{"id": "a", "text": "ElastiCache"}, {"id": "b", "text": "Glacier"}, {"id": "c", "text": "Athena"}, {"id": "d", "text": "EBS"}],
     "correct": ["a"], "explanation": "ElastiCache (Redis or Memcached) is an in-memory cache.",
     "exam_tracks": ["CLF_SAA"], "domains": ["Databases"], "related_services": ["elasticache"], "difficulty": 2,
     "professor_flock_hint": "In-memory and fast."},
    {"question_id": "clf_11", "prompt": "IAM is the right service for end-user application sign-in and sign-up.",
     "question_type": "truefalse", "answer_options": _TF, "correct": ["false"],
     "explanation": "IAM controls AWS resource permissions. End-user sign-in uses Cognito.",
     "exam_tracks": ["CLF_SAA"], "domains": ["Security"], "related_services": ["iam", "cognito"], "difficulty": 2,
     "professor_flock_hint": "IAM is for AWS access, not app users."},
    {"question_id": "clf_12", "prompt": "Which service securely stores and rotates database credentials and API keys?",
     "question_type": "mcq",
     "answer_options": [{"id": "a", "text": "KMS"}, {"id": "b", "text": "Secrets Manager"}, {"id": "c", "text": "WAF"}, {"id": "d", "text": "IAM"}],
     "correct": ["b"], "explanation": "Secrets Manager stores and rotates secrets. KMS manages encryption keys.",
     "exam_tracks": ["CLF_SAA"], "domains": ["Security"], "related_services": ["secrets_manager"], "difficulty": 2,
     "professor_flock_hint": "Secrets, not encryption keys themselves."},
    {"question_id": "clf_13", "prompt": "Which service is a columnar data warehouse for analytics over large datasets?",
     "question_type": "mcq",
     "answer_options": [{"id": "a", "text": "DynamoDB"}, {"id": "b", "text": "Redshift"}, {"id": "c", "text": "RDS"}, {"id": "d", "text": "ElastiCache"}],
     "correct": ["b"], "explanation": "Redshift is a columnar data warehouse for analytical queries.",
     "exam_tracks": ["CLF_SAA"], "domains": ["Analytics"], "related_services": ["redshift"], "difficulty": 2,
     "professor_flock_hint": "Warehouse means analytics at scale."},
    {"question_id": "clf_14", "prompt": "Pick the services for a serverless REST API with a NoSQL backend.",
     "question_type": "scenario_select",
     "answer_options": _svc(("api_gateway", "API Gateway"), ("lambda", "Lambda"), ("dynamodb", "DynamoDB"), ("ec2", "Amazon EC2"), ("rds", "Amazon RDS")),
     "correct": ["api_gateway", "lambda", "dynamodb"], "explanation": "API Gateway fronts Lambda functions that read and write DynamoDB. Fully serverless.",
     "exam_tracks": ["CLF_SAA"], "domains": ["Compute", "Integration"], "related_services": ["api_gateway", "lambda", "dynamodb"], "difficulty": 2,
     "professor_flock_hint": "Serverless front door, serverless compute, serverless NoSQL."},
    {"question_id": "clf_15", "prompt": "Which service provides block storage volumes attached to a single EC2 instance?",
     "question_type": "mcq",
     "answer_options": [{"id": "a", "text": "Amazon S3"}, {"id": "b", "text": "Amazon EFS"}, {"id": "c", "text": "Amazon EBS"}, {"id": "d", "text": "Glacier"}],
     "correct": ["c"], "explanation": "EBS is block storage for one instance. EFS is shared file storage. S3 is object storage.",
     "exam_tracks": ["CLF_SAA"], "domains": ["Storage"], "related_services": ["ebs"], "difficulty": 2,
     "professor_flock_hint": "Think of the VM's disk."},
    {"question_id": "clf_16", "prompt": "CloudWatch provides metrics, logs, and alarms for observability.",
     "question_type": "truefalse", "answer_options": _TF, "correct": ["true"],
     "explanation": "CloudWatch is the observability hub for metrics, logs, and alarms.",
     "exam_tracks": ["CLF_SAA"], "domains": ["Monitoring"], "related_services": ["cloudwatch"], "difficulty": 1,
     "professor_flock_hint": "Watch your metrics and logs."},

    # ---------------- AIF (AI Practitioner) ----------------
    {"question_id": "aif_01", "prompt": "Which service gives API access to foundation models without managing infrastructure?",
     "question_type": "mcq",
     "answer_options": [{"id": "a", "text": "SageMaker"}, {"id": "b", "text": "Bedrock"}, {"id": "c", "text": "Athena"}, {"id": "d", "text": "Redshift"}],
     "correct": ["b"], "explanation": "Bedrock provides foundation models through an API with no infrastructure to manage.",
     "exam_tracks": ["AIF"], "domains": ["Generative AI"], "related_services": ["bedrock"], "difficulty": 1,
     "professor_flock_hint": "Foundation models, no servers."},
    {"question_id": "aif_02", "prompt": "Amazon Bedrock lets you use foundation models without provisioning servers.",
     "question_type": "truefalse", "answer_options": _TF, "correct": ["true"],
     "explanation": "Bedrock is fully managed access to foundation models.",
     "exam_tracks": ["AIF"], "domains": ["Generative AI"], "related_services": ["bedrock"], "difficulty": 1,
     "professor_flock_hint": "Managed means no servers for you."},
    {"question_id": "aif_03", "prompt": "Retrieval augmented generation (RAG) improves answers by combining a foundation model with what?",
     "question_type": "mcq",
     "answer_options": [{"id": "a", "text": "A larger GPU cluster"}, {"id": "b", "text": "Your own data retrieved at query time"}, {"id": "c", "text": "More training epochs"}, {"id": "d", "text": "A relational database index"}],
     "correct": ["b"], "explanation": "RAG retrieves relevant context from your own data and feeds it to the model at query time.",
     "exam_tracks": ["AIF"], "domains": ["Generative AI"], "related_services": ["bedrock"], "difficulty": 2,
     "professor_flock_hint": "Retrieval means pulling in your own context."},
    {"question_id": "aif_04", "prompt": "Prompt engineering has no effect on the quality of foundation model output.",
     "question_type": "truefalse", "answer_options": _TF, "correct": ["false"],
     "explanation": "Clear prompts strongly influence output quality. Prompt engineering matters.",
     "exam_tracks": ["AIF"], "domains": ["AI/ML Fundamentals"], "related_services": ["bedrock"], "difficulty": 1,
     "professor_flock_hint": "How you ask changes what you get."},
    {"question_id": "aif_05", "prompt": "Which choice best describes a foundation model?",
     "question_type": "mcq",
     "answer_options": [{"id": "a", "text": "A small rules engine"}, {"id": "b", "text": "A large pretrained model adaptable to many tasks"}, {"id": "c", "text": "A relational database schema"}, {"id": "d", "text": "A network load balancer"}],
     "correct": ["b"], "explanation": "Foundation models are large, pretrained, and adaptable to many downstream tasks.",
     "exam_tracks": ["AIF"], "domains": ["AI/ML Fundamentals"], "related_services": ["bedrock"], "difficulty": 1,
     "professor_flock_hint": "Pretrained and general purpose."},

    # ---------------- MLA (ML Associate) ----------------
    {"question_id": "mla_01", "prompt": "Which service builds, trains, and deploys custom machine learning models end to end?",
     "question_type": "mcq",
     "answer_options": [{"id": "a", "text": "Bedrock"}, {"id": "b", "text": "SageMaker"}, {"id": "c", "text": "Athena"}, {"id": "d", "text": "CloudWatch"}],
     "correct": ["b"], "explanation": "SageMaker covers the full custom ML lifecycle. Bedrock is for foundation models.",
     "exam_tracks": ["MLA"], "domains": ["ML Engineering"], "related_services": ["sagemaker"], "difficulty": 1,
     "professor_flock_hint": "Custom training end to end."},
    {"question_id": "mla_02", "prompt": "SageMaker is mainly for prompt-only generative tasks, not custom model training.",
     "question_type": "truefalse", "answer_options": _TF, "correct": ["false"],
     "explanation": "SageMaker is for building and training custom models. Prompt-only tasks fit Bedrock.",
     "exam_tracks": ["MLA"], "domains": ["ML Engineering"], "related_services": ["sagemaker", "bedrock"], "difficulty": 2,
     "professor_flock_hint": "Custom training is SageMaker's job."},
    {"question_id": "mla_03", "prompt": "Pick the services to prepare and query ML training data sitting in an S3 data lake.",
     "question_type": "scenario_select",
     "answer_options": _svc(("s3", "Amazon S3"), ("glue_catalog", "Glue Data Catalog"), ("athena", "Athena"), ("rds", "Amazon RDS"), ("cloudfront", "CloudFront")),
     "correct": ["s3", "glue_catalog", "athena"], "explanation": "S3 holds the data, Glue catalogs the schema, and Athena runs serverless SQL for exploration.",
     "exam_tracks": ["MLA"], "domains": ["Data Preparation"], "related_services": ["s3", "glue_catalog", "athena"], "difficulty": 2,
     "professor_flock_hint": "Storage, catalog, and serverless SQL over the lake."},
    {"question_id": "mla_04", "prompt": "Which service runs serverless SQL directly over data in S3, with no cluster to manage?",
     "question_type": "mcq",
     "answer_options": [{"id": "a", "text": "Redshift"}, {"id": "b", "text": "Athena"}, {"id": "c", "text": "RDS"}, {"id": "d", "text": "DynamoDB"}],
     "correct": ["b"], "explanation": "Athena queries S3 data with serverless SQL. Redshift needs a cluster.",
     "exam_tracks": ["MLA"], "domains": ["Data Preparation"], "related_services": ["athena"], "difficulty": 2,
     "professor_flock_hint": "Serverless SQL over the data lake."},
    {"question_id": "mla_05", "prompt": "A data catalog such as Glue stores schema and metadata that power serverless SQL queries.",
     "question_type": "truefalse", "answer_options": _TF, "correct": ["true"],
     "explanation": "Glue Data Catalog holds table definitions and metadata used by Athena and Redshift.",
     "exam_tracks": ["MLA"], "domains": ["Data Preparation"], "related_services": ["glue_catalog"], "difficulty": 1,
     "professor_flock_hint": "Catalog equals schema and metadata."},

    # ---------------- AIF (expanded) ----------------
    {"question_id": "aif_06", "prompt": "A team wants a chatbot that answers using the company's own documents. Which approach fits best?",
     "question_type": "mcq",
     "answer_options": [{"id": "a", "text": "Retrieval augmented generation with a foundation model"}, {"id": "b", "text": "Train a model from scratch"}, {"id": "c", "text": "A relational database view"}, {"id": "d", "text": "A larger EC2 instance"}],
     "correct": ["a"], "explanation": "RAG retrieves the company's documents at query time and feeds them to a foundation model, avoiding costly custom training.",
     "exam_tracks": ["AIF"], "domains": ["Generative AI"], "related_services": ["bedrock"], "difficulty": 2,
     "professor_flock_hint": "Answer from your own documents means retrieval."},
    {"question_id": "aif_07", "prompt": "Which principle is part of responsible AI?",
     "question_type": "mcq",
     "answer_options": [{"id": "a", "text": "Maximize model size at all costs"}, {"id": "b", "text": "Fairness, transparency, and accountability"}, {"id": "c", "text": "Hide how decisions are made"}, {"id": "d", "text": "Ignore data privacy"}],
     "correct": ["b"], "explanation": "Responsible AI emphasizes fairness, transparency, privacy, and accountability.",
     "exam_tracks": ["AIF"], "domains": ["Responsible AI"], "related_services": [], "difficulty": 1,
     "professor_flock_hint": "Think fair, clear, and accountable."},
    {"question_id": "aif_08", "prompt": "Biased or unrepresentative training data can lead to unfair model outcomes.",
     "question_type": "truefalse", "answer_options": _TF, "correct": ["true"],
     "explanation": "Skewed data can produce biased results, so teams evaluate and mitigate bias.",
     "exam_tracks": ["AIF"], "domains": ["Responsible AI"], "related_services": [], "difficulty": 1,
     "professor_flock_hint": "Biased data in can mean biased results out."},
    {"question_id": "aif_09", "prompt": "Which service is a generative AI assistant that can connect to enterprise data and AWS?",
     "question_type": "mcq",
     "answer_options": [{"id": "a", "text": "Amazon Q"}, {"id": "b", "text": "Amazon Athena"}, {"id": "c", "text": "Amazon EBS"}, {"id": "d", "text": "Amazon Route 53"}],
     "correct": ["a"], "explanation": "Amazon Q is a generative AI assistant for business and developer tasks across your data and tools.",
     "exam_tracks": ["AIF"], "domains": ["Generative AI"], "related_services": [], "difficulty": 1,
     "professor_flock_hint": "The assistant that works across your data."},
    {"question_id": "aif_10", "prompt": "What most directly increases generative AI cost?",
     "question_type": "mcq",
     "answer_options": [{"id": "a", "text": "Using shorter prompts"}, {"id": "b", "text": "Larger models, more tokens, and bigger context"}, {"id": "c", "text": "Fewer requests"}, {"id": "d", "text": "Caching responses"}],
     "correct": ["b"], "explanation": "Cost scales with model size, token usage, request volume, and context length.",
     "exam_tracks": ["AIF"], "domains": ["Generative AI"], "related_services": ["bedrock"], "difficulty": 2,
     "professor_flock_hint": "Bigger and longer usually costs more."},
    {"question_id": "aif_11", "prompt": "You should place database passwords directly inside model prompts for convenience.",
     "question_type": "truefalse", "answer_options": _TF, "correct": ["false"],
     "explanation": "Sensitive secrets should never be sent into prompts. Protect data and use least privilege.",
     "exam_tracks": ["AIF"], "domains": ["Responsible AI"], "related_services": [], "difficulty": 2,
     "professor_flock_hint": "Secrets do not belong in prompts."},
    {"question_id": "aif_12", "prompt": "Which task is a good fit for a managed foundation model rather than a custom trained model?",
     "question_type": "mcq",
     "answer_options": [{"id": "a", "text": "Summarizing text with a general model"}, {"id": "b", "text": "A highly specialized model on proprietary sensor data"}, {"id": "c", "text": "A narrow rules-only workflow"}, {"id": "d", "text": "A simple database lookup"}],
     "correct": ["a"], "explanation": "General tasks like summarization suit a foundation model. Specialized needs may justify custom training.",
     "exam_tracks": ["AIF"], "domains": ["AI/ML Fundamentals"], "related_services": ["bedrock"], "difficulty": 2,
     "professor_flock_hint": "General task, general model."},
    {"question_id": "aif_13", "prompt": "Why evaluate a model before and after deployment?",
     "question_type": "mcq",
     "answer_options": [{"id": "a", "text": "To confirm outputs are accurate, relevant, and safe"}, {"id": "b", "text": "To increase token cost"}, {"id": "c", "text": "To avoid using test data"}, {"id": "d", "text": "To skip human review"}],
     "correct": ["a"], "explanation": "Evaluation checks quality and safety using test data and human review over time.",
     "exam_tracks": ["AIF"], "domains": ["AI/ML Fundamentals"], "related_services": [], "difficulty": 2,
     "professor_flock_hint": "You cannot trust what you have not measured."},
    {"question_id": "aif_14", "prompt": "Clear instructions and examples in a prompt can improve a foundation model's output.",
     "question_type": "truefalse", "answer_options": _TF, "correct": ["true"],
     "explanation": "Prompt engineering shapes output quality and format.",
     "exam_tracks": ["AIF"], "domains": ["AI/ML Fundamentals"], "related_services": ["bedrock"], "difficulty": 1,
     "professor_flock_hint": "How you ask matters."},
    {"question_id": "aif_15", "prompt": "Which best describes when to choose a custom trained model over a foundation model?",
     "question_type": "mcq",
     "answer_options": [{"id": "a", "text": "When a specialized task needs learning from your unique labeled data"}, {"id": "b", "text": "For every text summarization task"}, {"id": "c", "text": "Whenever you want the simplest option"}, {"id": "d", "text": "Only to reduce cost"}],
     "correct": ["a"], "explanation": "Custom training fits specialized problems that need your own labeled data. General tasks fit foundation models.",
     "exam_tracks": ["AIF"], "domains": ["AI/ML Fundamentals"], "related_services": ["sagemaker"], "difficulty": 3,
     "professor_flock_hint": "Unique data and a narrow task point to custom training."},

    # ---------------- MLA (expanded) ----------------
    {"question_id": "mla_06", "prompt": "Which SageMaker capability serves a model for low-latency real-time predictions over an API?",
     "question_type": "mcq",
     "answer_options": [{"id": "a", "text": "A training job"}, {"id": "b", "text": "An endpoint"}, {"id": "c", "text": "A crawler"}, {"id": "d", "text": "A data catalog"}],
     "correct": ["b"], "explanation": "A SageMaker endpoint hosts a model for real-time inference.",
     "exam_tracks": ["MLA"], "domains": ["ML Engineering"], "related_services": ["sagemaker"], "difficulty": 2,
     "professor_flock_hint": "Endpoints serve predictions in real time."},
    {"question_id": "mla_07", "prompt": "A model performs well on training data but poorly on new data. What is this?",
     "question_type": "mcq",
     "answer_options": [{"id": "a", "text": "Underfitting"}, {"id": "b", "text": "Overfitting"}, {"id": "c", "text": "Data partitioning"}, {"id": "d", "text": "Feature scaling"}],
     "correct": ["b"], "explanation": "Overfitting means the model memorized training data and fails to generalize.",
     "exam_tracks": ["MLA"], "domains": ["ML Engineering"], "related_services": [], "difficulty": 2,
     "professor_flock_hint": "Great on training, poor on new data."},
    {"question_id": "mla_08", "prompt": "Scoring a very large dataset overnight on a schedule is best done with real-time endpoints.",
     "question_type": "truefalse", "answer_options": _TF, "correct": ["false"],
     "explanation": "Large scheduled scoring fits batch inference, which is often cheaper than real-time endpoints.",
     "exam_tracks": ["MLA"], "domains": ["ML Engineering"], "related_services": ["sagemaker"], "difficulty": 2,
     "professor_flock_hint": "Big offline jobs point to batch."},
    {"question_id": "mla_09", "prompt": "Which component provides consistent, reusable features for both training and inference?",
     "question_type": "mcq",
     "answer_options": [{"id": "a", "text": "Feature Store"}, {"id": "b", "text": "Model Registry"}, {"id": "c", "text": "CloudFront"}, {"id": "d", "text": "Route 53"}],
     "correct": ["a"], "explanation": "A Feature Store centralizes curated features so training and serving stay consistent.",
     "exam_tracks": ["MLA"], "domains": ["ML Engineering"], "related_services": [], "difficulty": 2,
     "professor_flock_hint": "One source of truth for features."},
    {"question_id": "mla_10", "prompt": "Which component versions models and tracks their approval for promotion to production?",
     "question_type": "mcq",
     "answer_options": [{"id": "a", "text": "Model Registry"}, {"id": "b", "text": "Feature Store"}, {"id": "c", "text": "Athena"}, {"id": "d", "text": "S3 Glacier"}],
     "correct": ["a"], "explanation": "The Model Registry versions models and manages approval status.",
     "exam_tracks": ["MLA"], "domains": ["MLOps"], "related_services": [], "difficulty": 2,
     "professor_flock_hint": "Versioning and approvals live here."},
    {"question_id": "mla_11", "prompt": "Why monitor a model after deployment?",
     "question_type": "mcq",
     "answer_options": [{"id": "a", "text": "To detect data drift and quality drops"}, {"id": "b", "text": "To stop all logging"}, {"id": "c", "text": "To avoid retraining ever"}, {"id": "d", "text": "To hide metrics"}],
     "correct": ["a"], "explanation": "Monitoring catches drift and degradation so you can retrain in time.",
     "exam_tracks": ["MLA"], "domains": ["MLOps"], "related_services": [], "difficulty": 2,
     "professor_flock_hint": "Models decay as the world changes."},
    {"question_id": "mla_12", "prompt": "MLOps applies automation and reliability practices across the ML lifecycle.",
     "question_type": "truefalse", "answer_options": _TF, "correct": ["true"],
     "explanation": "MLOps brings DevOps discipline to data prep, training, deployment, monitoring, and retraining.",
     "exam_tracks": ["MLA"], "domains": ["MLOps"], "related_services": [], "difficulty": 1,
     "professor_flock_hint": "DevOps discipline for ML."},
    {"question_id": "mla_13", "prompt": "Which SageMaker feature defines a repeatable multi-step ML workflow?",
     "question_type": "mcq",
     "answer_options": [{"id": "a", "text": "Pipelines"}, {"id": "b", "text": "Endpoints"}, {"id": "c", "text": "Crawlers"}, {"id": "d", "text": "Buckets"}],
     "correct": ["a"], "explanation": "SageMaker Pipelines connect steps like prep, training, evaluation, and registration.",
     "exam_tracks": ["MLA"], "domains": ["MLOps"], "related_services": [], "difficulty": 2,
     "professor_flock_hint": "Repeatable connected steps."},
    {"question_id": "mla_14", "prompt": "Why track experiments with parameters, data versions, and metrics?",
     "question_type": "mcq",
     "answer_options": [{"id": "a", "text": "To compare runs and reproduce the best model"}, {"id": "b", "text": "To increase randomness"}, {"id": "c", "text": "To hide results"}, {"id": "d", "text": "To avoid validation"}],
     "correct": ["a"], "explanation": "Experiment tracking enables comparison and reproducibility.",
     "exam_tracks": ["MLA"], "domains": ["MLOps"], "related_services": [], "difficulty": 2,
     "professor_flock_hint": "If you cannot reproduce it, you cannot trust it."},
    {"question_id": "mla_15", "prompt": "Good feature engineering and clean data often improve results more than a fancier model.",
     "question_type": "truefalse", "answer_options": _TF, "correct": ["true"],
     "explanation": "Quality inputs frequently matter more than model complexity.",
     "exam_tracks": ["MLA"], "domains": ["Data Preparation"], "related_services": [], "difficulty": 2,
     "professor_flock_hint": "Better inputs usually beat fancier models."},

    # ---------------- DEA (Data Engineer Associate) ----------------
    {"question_id": "dea_01", "prompt": "Which service is the durable, low-cost foundation for storing a data lake of any format?",
     "question_type": "mcq",
     "answer_options": [{"id": "a", "text": "Amazon S3"}, {"id": "b", "text": "Amazon EBS"}, {"id": "c", "text": "DynamoDB"}, {"id": "d", "text": "ElastiCache"}],
     "correct": ["a"], "explanation": "S3 stores raw and processed data durably and cheaply, decoupled from query engines.",
     "exam_tracks": ["DEA"], "domains": ["Storage"], "related_services": ["s3"], "difficulty": 1,
     "professor_flock_hint": "Store once, query with many engines."},
    {"question_id": "dea_02", "prompt": "Which service runs serverless SQL directly over data in S3?",
     "question_type": "mcq",
     "answer_options": [{"id": "a", "text": "Amazon Athena"}, {"id": "b", "text": "Amazon RDS"}, {"id": "c", "text": "Amazon MSK"}, {"id": "d", "text": "Amazon EBS"}],
     "correct": ["a"], "explanation": "Athena queries S3 with serverless SQL and no cluster to manage.",
     "exam_tracks": ["DEA"], "domains": ["Analytics"], "related_services": ["athena"], "difficulty": 1,
     "professor_flock_hint": "Serverless SQL over the lake."},
    {"question_id": "dea_03", "prompt": "Which service is a columnar data warehouse for large-scale analytics?",
     "question_type": "mcq",
     "answer_options": [{"id": "a", "text": "Amazon Redshift"}, {"id": "b", "text": "DynamoDB"}, {"id": "c", "text": "Amazon SQS"}, {"id": "d", "text": "Amazon Cognito"}],
     "correct": ["a"], "explanation": "Redshift is a columnar warehouse built for analytical queries.",
     "exam_tracks": ["DEA"], "domains": ["Analytics"], "related_services": ["redshift"], "difficulty": 1,
     "professor_flock_hint": "Warehouse for analytics at scale."},
    {"question_id": "dea_04", "prompt": "Which service ingests high-volume streaming data in near real time?",
     "question_type": "mcq",
     "answer_options": [{"id": "a", "text": "Amazon Kinesis"}, {"id": "b", "text": "Amazon Glacier"}, {"id": "c", "text": "Amazon RDS"}, {"id": "d", "text": "Amazon EFS"}],
     "correct": ["a"], "explanation": "Kinesis ingests streaming data such as clickstream and telemetry.",
     "exam_tracks": ["DEA"], "domains": ["Integration"], "related_services": ["kinesis"], "difficulty": 2,
     "professor_flock_hint": "Streaming ingestion in near real time."},
    {"question_id": "dea_05", "prompt": "Which service holds table and schema metadata used by Athena and Redshift Spectrum?",
     "question_type": "mcq",
     "answer_options": [{"id": "a", "text": "AWS Glue Data Catalog"}, {"id": "b", "text": "Amazon S3"}, {"id": "c", "text": "Amazon SNS"}, {"id": "d", "text": "AWS WAF"}],
     "correct": ["a"], "explanation": "The Glue Data Catalog stores schema and metadata for query engines.",
     "exam_tracks": ["DEA"], "domains": ["Analytics"], "related_services": ["glue_catalog"], "difficulty": 2,
     "professor_flock_hint": "Catalog equals schema and metadata."},
    {"question_id": "dea_06", "prompt": "Partitioning data in a lake by keys like date reduces the amount of data scanned per query.",
     "question_type": "truefalse", "answer_options": _TF, "correct": ["true"],
     "explanation": "Good partitions cut cost and improve performance by scanning less data.",
     "exam_tracks": ["DEA"], "domains": ["Analytics"], "related_services": ["athena", "s3"], "difficulty": 2,
     "professor_flock_hint": "Less data scanned means faster and cheaper."},
    {"question_id": "dea_07", "prompt": "Which service orchestrates multi-step workflows with state, retries, and branching?",
     "question_type": "mcq",
     "answer_options": [{"id": "a", "text": "AWS Step Functions"}, {"id": "b", "text": "Amazon S3"}, {"id": "c", "text": "Amazon ElastiCache"}, {"id": "d", "text": "Amazon EBS"}],
     "correct": ["a"], "explanation": "Step Functions coordinate ordered steps with retries and branching.",
     "exam_tracks": ["DEA"], "domains": ["Orchestration"], "related_services": [], "difficulty": 2,
     "professor_flock_hint": "Ordered steps with retries and branching."},
    {"question_id": "dea_08", "prompt": "Which service routes events with rules and schedules to trigger data jobs?",
     "question_type": "mcq",
     "answer_options": [{"id": "a", "text": "Amazon EventBridge"}, {"id": "b", "text": "Amazon Redshift"}, {"id": "c", "text": "Amazon EFS"}, {"id": "d", "text": "AWS KMS"}],
     "correct": ["a"], "explanation": "EventBridge triggers event-driven and scheduled workflows.",
     "exam_tracks": ["DEA"], "domains": ["Orchestration"], "related_services": ["eventbridge"], "difficulty": 2,
     "professor_flock_hint": "Event-driven and scheduled triggers."},
    {"question_id": "dea_09", "prompt": "Which service centralizes fine-grained access permissions across data lake tables and columns?",
     "question_type": "mcq",
     "answer_options": [{"id": "a", "text": "AWS Lake Formation"}, {"id": "b", "text": "Amazon CloudFront"}, {"id": "c", "text": "Amazon SQS"}, {"id": "d", "text": "Amazon Athena"}],
     "correct": ["a"], "explanation": "Lake Formation applies fine-grained governance across the data lake.",
     "exam_tracks": ["DEA"], "domains": ["Governance"], "related_services": [], "difficulty": 2,
     "professor_flock_hint": "Central, fine-grained lake governance."},
    {"question_id": "dea_10", "prompt": "A nightly load of data in scheduled chunks is an example of streaming ingestion.",
     "question_type": "truefalse", "answer_options": _TF, "correct": ["false"],
     "explanation": "Scheduled chunk loads are batch ingestion. Streaming ingests data continuously.",
     "exam_tracks": ["DEA"], "domains": ["Integration"], "related_services": ["kinesis"], "difficulty": 1,
     "professor_flock_hint": "Scheduled chunks are batch, continuous is streaming."},
    {"question_id": "dea_11", "prompt": "Pick the services for a serverless pipeline that catalogs S3 data and queries it with SQL.",
     "question_type": "scenario_select",
     "answer_options": _svc(("s3", "Amazon S3"), ("glue_catalog", "Glue Data Catalog"), ("athena", "Athena"), ("rds", "Amazon RDS"), ("cloudfront", "CloudFront")),
     "correct": ["s3", "glue_catalog", "athena"], "explanation": "S3 stores the data, the Glue Data Catalog holds schema, and Athena runs serverless SQL.",
     "exam_tracks": ["DEA"], "domains": ["Analytics"], "related_services": ["s3", "glue_catalog", "athena"], "difficulty": 2,
     "professor_flock_hint": "Storage, catalog, and serverless SQL."},
    {"question_id": "dea_12", "prompt": "Data quality checks validate completeness and accuracy before data reaches consumers.",
     "question_type": "truefalse", "answer_options": _TF, "correct": ["true"],
     "explanation": "Quality rules catch bad data early so it does not spread downstream.",
     "exam_tracks": ["DEA"], "domains": ["Data Quality"], "related_services": [], "difficulty": 1,
     "professor_flock_hint": "Catch bad data before it spreads."},
    {"question_id": "dea_13", "prompt": "Which pattern moves rarely accessed data to cheaper storage over time?",
     "question_type": "mcq",
     "answer_options": [{"id": "a", "text": "Data lifecycle policies"}, {"id": "b", "text": "Real-time endpoints"}, {"id": "c", "text": "Prompt engineering"}, {"id": "d", "text": "Fan-out messaging"}],
     "correct": ["a"], "explanation": "Lifecycle policies tier or expire data to control cost as access drops.",
     "exam_tracks": ["DEA"], "domains": ["Storage"], "related_services": ["s3", "glacier"], "difficulty": 2,
     "professor_flock_hint": "Age cold data to cheaper tiers."},
]

_BY_ID = {q["question_id"]: q for q in QUESTIONS}


def _sanitize(q: Dict[str, Any]) -> Dict[str, Any]:
    return {k: v for k, v in q.items() if k != "correct"}


def session_questions(track: str, n: int = SESSION_SIZE):
    pool = [q for q in QUESTIONS if track == "MIXED" or track in q.get("exam_tracks", [])]
    random.shuffle(pool)
    chosen = pool[:n]
    return [_sanitize(q) for q in chosen], len(pool) < n, len(pool)


def grade_answers(submitted: List[Dict[str, Any]]):
    correct_count = 0
    per_question = []
    domain_total, domain_correct = {}, {}
    for ans in submitted:
        q = _BY_ID.get(ans.get("question_id"))
        if not q:
            continue
        sel = ans.get("selected")
        sel_set = set(sel) if isinstance(sel, list) else ({sel} if sel else set())
        correct_set = set(q["correct"])
        is_correct = sel_set == correct_set
        if is_correct:
            correct_count += 1
        for d in q.get("domains", []):
            domain_total[d] = domain_total.get(d, 0) + 1
            if is_correct:
                domain_correct[d] = domain_correct.get(d, 0) + 1
        per_question.append({
            "question_id": q["question_id"], "prompt": q["prompt"],
            "question_type": q["question_type"], "answer_options": q["answer_options"],
            "selected": sorted(sel_set), "correct": q["correct"], "is_correct": is_correct,
            "explanation": q["explanation"], "related_services": q.get("related_services", []),
            "domains": q.get("domains", []), "professor_flock_hint": q.get("professor_flock_hint", ""),
        })
    total = len(per_question)
    score = round((correct_count / total) * 100) if total else 0
    strengths = sorted(d for d in domain_total if domain_correct.get(d, 0) == domain_total[d])
    review_areas = sorted(d for d in domain_total if domain_correct.get(d, 0) < domain_total[d])
    return {
        "score": score, "correct_count": correct_count, "total": total,
        "per_question": per_question, "strengths": strengths, "review_areas": review_areas,
    }
